window.TDAT_ROLE_FAMILIES = [
  {
    id: "corporate-finance-fpa",
    label: "Corporate Finance & FP&A",
    roles: ["CFO Office", "Corporate Finance", "Financial Reporting", "Finance Business Partner", "FP&A", "Fractional CFO", "Regional Finance"],
  },
  {
    id: "commercial-operational-finance",
    label: "Commercial & Operational Finance",
    roles: ["Commercial Finance", "HR Finance", "Operations Finance", "Pricing Finance", "Sales Finance"],
  },
  {
    id: "accounting-controllership",
    label: "Accounting & Controllership",
    roles: ["Accounting", "Controllership"],
  },
  {
    id: "investment-valuation-transactions",
    label: "Investment, Valuation & Transactions",
    roles: ["Corporate Development", "Equity Research", "Investment Analyst", "Investment Banking", "Leveraged Finance", "M&A Advisory", "Private Equity", "Valuation Advisory", "Venture Capital"],
  },
  {
    id: "treasury-funding-real-assets",
    label: "Treasury, Funding & Real Assets",
    roles: ["Infrastructure Finance", "Project Finance", "Structured Finance", "Treasury"],
  },
  {
    id: "banking-credit-risk",
    label: "Banking, Credit & Risk",
    roles: ["Banking Finance", "Commercial Banking", "Credit Analysis", "Credit Risk", "Enterprise Risk", "Lending", "Market Risk", "Portfolio Risk", "Risk Analytics"],
  },
  {
    id: "sme-startup-personal-finance",
    label: "SME, Startup & Personal Finance",
    roles: ["Financial Education / Learner", "Founder", "Individual / Household", "SME Finance", "Startup Finance"],
  },
];

window.TDAT_MODEL_LIBRARY = [
  {
    id: "TDAT-FM-CORE-001",
    slug: "three-statement-model",
    title: "Three-Statement Model Starter",
    decision: "How do five years of operating drivers flow through profit, cash, debt, and the balance sheet?",
    description: "Five-year integrated income statement, cash flow, and balance sheet. Explicit working-capital, PP&E, debt, and retained-earnings schedules. Visible driver ramps with ten calculation controls",
    domain: "Core Statements",
    roles: ["FP&A", "Corporate Finance", "Accounting", "Valuation Advisory"],
    useCases: ["Three statements","Driver ramps","Balance-sheet roll-forwards"],
    level: "Starter",
    status: "Available",
    priority: "P0",
    horizon: "Base plus five-year forecast",
    setup: "20-40 minutes",
    compatibility: "Excel 365",
    tags: ["Three statements","Driver ramps","Balance-sheet roll-forwards"],
    version: "1.4.0",
    lastTested: "2026-08-17",
    qa: "10 / 10 calculation controls PASS; 5 / 5 sheets rendered",
    file: {
      path: "three-statement-model/model/tdat-three-statement-model.xlsx",
      size: "26.1 KB",
      format: ".xlsx",
      macros: false,
      externalLinks: false,
      circularReferences: false,
      sha256: "16B5615E27167765E255A5FDFEBFA495E9D99D3230614400A4F8021EC08C2CDA",
    },
  },
  {
    id: "TDAT-FM-FPA-001",
    slug: "budget-rolling-forecast",
    title: "Budget & Rolling Forecast",
    decision: "Where will the next 12 months land versus budget?",
    description: "One 12-month revenue forecast. Revenue and EBITDA budget gaps. A simple operating cash proxy",
    domain: "Planning & Performance",
    roles: ["FP&A", "Finance Business Partner", "Corporate Finance"],
    useCases: ["Budget","Rolling forecast","EBITDA"],
    level: "Starter",
    status: "Available",
    priority: "P0",
    horizon: "Next 12 months",
    setup: "20-40 minutes",
    tags: ["Budget","Rolling forecast","EBITDA"],
    compatibility: "Excel 365",
    version: "1.4.0",
    lastTested: "2026-08-17",
    qa: "10 / 10 calculation controls PASS; 5 / 5 sheets rendered",
    file: {
      path: "budget-rolling-forecast/model/tdat-budget-rolling-forecast.xlsx",
      size: "18.2 KB",
      format: ".xlsx",
      macros: false,
      externalLinks: false,
      circularReferences: false,
      sha256: "4C41539A4EB4F34D7BCC9333F8F640B9F6621D2EE6DE7E0A4BF2DD2EAD12405C",
    },
  },
  {
    id: "TDAT-FM-TSY-001",
    slug: "thirteen-week-cash-flow",
    title: "13-Week Cash Flow",
    decision: "When will cash tighten, and how much facility is needed?",
    description: "A 13-week direct cash forecast. Automatic facility draw and repayment. Peak funding and closing liquidity",
    domain: "Treasury & Capital",
    roles: ["Treasury", "FP&A", "CFO Office", "SME Finance"],
    useCases: ["Liquidity","Cash runway","Facility draw"],
    level: "Starter",
    status: "Available",
    priority: "P0",
    horizon: "13 weeks",
    setup: "20-40 minutes",
    tags: ["Liquidity","Cash runway","Facility draw"],
    compatibility: "Excel 365",
    version: "1.4.0",
    lastTested: "2026-08-17",
    qa: "10 / 10 calculation controls PASS; 5 / 5 sheets rendered",
    file: {
      path: "thirteen-week-cash-flow/model/tdat-thirteen-week-cash-flow.xlsx",
      size: "18.6 KB",
      format: ".xlsx",
      macros: false,
      externalLinks: false,
      circularReferences: false,
      sha256: "31F382DB158E752C6B21391353A948FFE25B5622D496AF96A9692BF81F165E2D",
    },
  },
  {
    id: "TDAT-FM-VAL-001",
    slug: "dcf-valuation",
    title: "DCF Valuation",
    decision: "What are the business and equity worth under one driver-based operating case?",
    description: "Five-year driver-based free-cash-flow build. Terminal-value and enterprise-to-equity bridges. Value per share and ten calculation controls",
    domain: "Valuation & Transactions",
    roles: ["Valuation Advisory", "Corporate Development", "Equity Research", "Investment Banking"],
    useCases: ["DCF","Free Cash Flow","Enterprise Value"],
    level: "Starter",
    status: "Available",
    priority: "P0",
    horizon: "5 years",
    setup: "20-40 minutes",
    tags: ["DCF","Free Cash Flow","Enterprise Value"],
    compatibility: "Excel 365",
    version: "1.4.0",
    lastTested: "2026-08-17",
    qa: "10 / 10 calculation controls PASS; 5 / 5 sheets rendered",
    file: {
      path: "dcf-valuation/model/tdat-dcf-valuation.xlsx",
      size: "18.1 KB",
      format: ".xlsx",
      macros: false,
      externalLinks: false,
      circularReferences: false,
      sha256: "403406E0578EEA7E9A44956E847980B056B0230E971906E761C4627A1C5093A9",
    },
  },
  {
    id: "TDAT-FM-INV-001",
    slug: "capex-business-case",
    title: "Capex / Business Case",
    decision: "Does this investment create value and repay itself fast enough?",
    description: "One investment and one benefit stream. NPV, IRR, and payback. Final salvage and working-capital recovery",
    domain: "Investment & Portfolio",
    roles: ["FP&A", "Corporate Finance", "Investment Analyst", "Operations Finance"],
    useCases: ["Capex","NPV","Payback"],
    level: "Starter",
    status: "Available",
    priority: "P0",
    horizon: "Year 0 plus five years",
    setup: "20-40 minutes",
    tags: ["Capex","NPV","Payback"],
    compatibility: "Excel 365",
    version: "1.4.0",
    lastTested: "2026-08-17",
    qa: "10 / 10 calculation controls PASS; 5 / 5 sheets rendered",
    file: {
      path: "capex-business-case/model/tdat-capex-business-case.xlsx",
      size: "17.6 KB",
      format: ".xlsx",
      macros: false,
      externalLinks: false,
      circularReferences: false,
      sha256: "67972F9D781480408C6EEA8BE68B3CD179EBE5BAE7B839E30EE2D6E62216467F",
    },
  },
  {
    id: "TDAT-FM-FPA-002",
    slug: "working-capital-planner",
    title: "Working Capital Planner",
    decision: "How much cash would better DSO, DIO, and DPO release?",
    description: "Current-to-target five-column phase-in. DSO, DIO, and DPO balance schedules. Incremental and cumulative cash release",
    domain: "Planning & Performance",
    roles: ["FP&A", "Treasury", "Commercial Finance", "Accounting"],
    useCases: ["Working capital","Cash release","CCC"],
    level: "Starter",
    status: "Available",
    priority: "P1",
    horizon: "Current plus four-step improvement path",
    setup: "20-40 minutes",
    tags: ["Working capital","Cash release","CCC"],
    compatibility: "Excel 365",
    version: "1.4.0",
    lastTested: "2026-08-17",
    qa: "10 / 10 calculation controls PASS; 5 / 5 sheets rendered",
    file: {
      path: "working-capital-planner/model/tdat-working-capital-planner.xlsx",
      size: "17.0 KB",
      format: ".xlsx",
      macros: false,
      externalLinks: false,
      circularReferences: false,
      sha256: "F4E42361BBF649ACD676120B6E38DC1D532F8AC55632075985E40FDADDFEE170",
    },
  },
  {
    id: "TDAT-FM-FPA-003",
    slug: "variance-bridge-forecast-accuracy",
    title: "Variance Bridge & Forecast Accuracy",
    decision: "Which driver caused the EBITDA gap versus budget?",
    description: "Budget and actual operating P&Ls. Price, volume, cost, and opex bridge. Revenue forecast accuracy and ten controls",
    domain: "Planning & Performance",
    roles: ["FP&A", "Commercial Finance", "Finance Business Partner"],
    useCases: ["Variance bridge","Price-volume-cost","Forecast accuracy"],
    level: "Starter",
    status: "Available",
    priority: "P1",
    horizon: "One period",
    setup: "20-40 minutes",
    tags: ["Variance bridge","Price-volume-cost","Forecast accuracy"],
    compatibility: "Excel 365",
    version: "1.4.0",
    lastTested: "2026-08-17",
    qa: "10 / 10 calculation controls PASS; 5 / 5 sheets rendered",
    file: {
      path: "variance-bridge-forecast-accuracy/model/tdat-variance-bridge-forecast-accuracy.xlsx",
      size: "17.3 KB",
      format: ".xlsx",
      macros: false,
      externalLinks: false,
      circularReferences: false,
      sha256: "FE76C7ED7CFAF98A628A2B54DC2C2B3E4BD949EBD16BABAC64483C318C34AE1D",
    },
  },
  {
    id: "TDAT-FM-FPA-004",
    slug: "headcount-compensation-plan",
    title: "Headcount & Compensation Plan",
    decision: "What will the hiring plan cost, and is it within budget?",
    description: "Twelve-month headcount roll-forward. Monthly salary, benefit, bonus, and payroll-tax build. Cumulative personnel cost, budget variance, and capacity",
    domain: "Planning & Performance",
    roles: ["FP&A", "HR Finance", "Finance Business Partner"],
    useCases: ["Headcount","Personnel cost","Capacity"],
    level: "Starter",
    status: "Available",
    priority: "P1",
    horizon: "One-year plan",
    setup: "20-40 minutes",
    tags: ["Headcount","Personnel cost","Capacity"],
    compatibility: "Excel 365",
    version: "1.4.0",
    lastTested: "2026-08-17",
    qa: "10 / 10 calculation controls PASS; 5 / 5 sheets rendered",
    file: {
      path: "headcount-compensation-plan/model/tdat-headcount-compensation-plan.xlsx",
      size: "19.4 KB",
      format: ".xlsx",
      macros: false,
      externalLinks: false,
      circularReferences: false,
      sha256: "A386C37D3588FCC899E4DA7FA78BEB615C28B47205203C46DD90C7820EFC7D0C",
    },
  },
  {
    id: "TDAT-FM-VAL-002",
    slug: "trading-comps",
    title: "Trading Comparables",
    decision: "What share price does the peer set imply as EBITDA and net debt evolve over five years?",
    description: "Visible peer calibration and five-year EBITDA schedule. Multiple ramp and enterprise-to-equity bridge. Net-debt roll-forward, implied share price, and upside",
    domain: "Valuation & Transactions",
    roles: ["Investment Banking", "Equity Research", "Corporate Development", "Valuation Advisory"],
    useCases: ["Comps","EV / EBITDA","Share price"],
    level: "Starter",
    status: "Available",
    priority: "P1",
    horizon: "Base plus five forecast years",
    setup: "20-40 minutes",
    tags: ["Comps","EV / EBITDA","Share price"],
    compatibility: "Excel 365",
    version: "1.4.0",
    lastTested: "2026-08-17",
    qa: "10 / 10 calculation controls PASS; 5 / 5 sheets rendered",
    file: {
      path: "trading-comps/model/tdat-trading-comps.xlsx",
      size: "18.2 KB",
      format: ".xlsx",
      macros: false,
      externalLinks: false,
      circularReferences: false,
      sha256: "CF4B448510D1761E5F724BC985109E4CAEB0F6037E0D59D5EFF2F3FFF565E227",
    },
  },
  {
    id: "TDAT-FM-MA-001",
    slug: "ma-accretion-dilution",
    title: "M&A Accretion / Dilution",
    decision: "How do funding, synergy capture, and debt paydown affect EPS accretion over five years?",
    description: "Cash-and-stock consideration bridge. Five-year earnings, synergy, and acquisition-debt schedule. Pro forma EPS and accretion / dilution by year",
    domain: "Valuation & Transactions",
    roles: ["Investment Banking", "M&A Advisory", "Corporate Development"],
    useCases: ["M&A","EPS","Funding mix"],
    level: "Starter",
    status: "Available",
    priority: "P1",
    horizon: "Base plus five forecast years",
    setup: "20-40 minutes",
    tags: ["M&A","EPS","Funding mix"],
    compatibility: "Excel 365",
    version: "1.4.0",
    lastTested: "2026-08-17",
    qa: "10 / 10 calculation controls PASS; 5 / 5 sheets rendered",
    file: {
      path: "ma-accretion-dilution/model/tdat-ma-accretion-dilution.xlsx",
      size: "19.0 KB",
      format: ".xlsx",
      macros: false,
      externalLinks: false,
      circularReferences: false,
      sha256: "23DABDBB17B99E6AFD3737227D2156A5663684B5ADE33E8A2A15FF37EF604644",
    },
  },
  {
    id: "TDAT-FM-TSY-002",
    slug: "debt-covenant-model",
    title: "Debt & Covenant Model",
    decision: "Does the five-year forecast remain inside leverage, coverage, and DSCR covenants?",
    description: "Five-year EBITDA and debt roll-forward. Interest, CFADS, and debt-service bridge. Leverage, coverage, DSCR, and covenant headroom by year",
    domain: "Treasury & Capital",
    roles: ["Treasury", "Corporate Finance", "Credit Analysis", "FP&A"],
    useCases: ["Debt","Covenants","DSCR"],
    level: "Starter",
    status: "Available",
    priority: "P1",
    horizon: "Base plus five forecast years",
    setup: "20-40 minutes",
    tags: ["Debt","Covenants","DSCR"],
    compatibility: "Excel 365",
    version: "1.4.0",
    lastTested: "2026-08-17",
    qa: "10 / 10 calculation controls PASS; 5 / 5 sheets rendered",
    file: {
      path: "debt-covenant-model/model/tdat-debt-covenant-model.xlsx",
      size: "18.7 KB",
      format: ".xlsx",
      macros: false,
      externalLinks: false,
      circularReferences: false,
      sha256: "4D38486B3E8B6963FEE92223F7A3470CC96BD1D5F35573A5024756BEB168B859",
    },
  },
  {
    id: "TDAT-FM-RSK-001",
    slug: "credit-underwriting-dscr",
    title: "Credit Underwriting / DSCR",
    decision: "Can the borrower support the requested debt through a five-year underwritten forecast?",
    description: "Five-year normalized and underwritten EBITDA build. CFADS, debt service, and principal roll-forward. DSCR, leverage, cash headroom, and debt headroom",
    domain: "Credit & Risk",
    roles: ["Credit Analysis", "Enterprise Risk", "Commercial Banking", "Lending"],
    useCases: ["Credit","DSCR","Leverage"],
    level: "Starter",
    status: "Available",
    priority: "P1",
    horizon: "Base plus five forecast years",
    setup: "20-40 minutes",
    tags: ["Credit","DSCR","Leverage"],
    compatibility: "Excel 365",
    version: "1.4.0",
    lastTested: "2026-08-17",
    qa: "10 / 10 calculation controls PASS; 5 / 5 sheets rendered",
    file: {
      path: "credit-underwriting-dscr/model/tdat-credit-underwriting-dscr.xlsx",
      size: "18.8 KB",
      format: ".xlsx",
      macros: false,
      externalLinks: false,
      circularReferences: false,
      sha256: "467262AEFE9210C530212DF8F220C8DFF86292CE6B5628482DDEDBCFABF0DAA1",
    },
  },
  {
    id: "TDAT-FM-PF-001",
    slug: "project-finance-lite",
    title: "Project Finance Lite",
    decision: "Can the project fund construction, service debt, and deliver acceptable project and equity returns?",
    description: "Construction funding and debt / equity sources bridge. Five-year operating cash flow and level debt-service schedule. Project IRR, equity IRR, DSCR, and debt paydown",
    domain: "Project & Real Assets",
    roles: ["Project Finance", "Infrastructure Finance", "Lending", "Investment Analyst"],
    useCases: ["Project finance","DSCR","IRR"],
    level: "Starter",
    status: "Available",
    priority: "P1",
    horizon: "Funding at Year 0 plus five operating years",
    setup: "20-40 minutes",
    tags: ["Project finance","DSCR","IRR"],
    compatibility: "Excel 365",
    version: "1.4.0",
    lastTested: "2026-08-17",
    qa: "10 / 10 calculation controls PASS; 5 / 5 sheets rendered",
    file: {
      path: "project-finance-lite/model/tdat-project-finance-lite.xlsx",
      size: "19.4 KB",
      format: ".xlsx",
      macros: false,
      externalLinks: false,
      circularReferences: false,
      sha256: "6D754C5B4403AB59A7062E284E2DAAA8AE813CC1A9DF5B39E6FE091AA652A85F",
    },
  },
  {
    id: "TDAT-FM-SME-001",
    slug: "sme-integrated-forecast",
    title: "SME Integrated Forecast",
    decision: "When does the business reach EBITDA break-even, and how much liquidity is required over the next 12 months?",
    description: "Monthly revenue, gross profit, and EBITDA forecast. Receivables, payables, and net-working-capital bridge. Cash roll-forward, minimum-cash funding, and break-even timing",
    domain: "SME & Startup",
    roles: ["SME Finance", "Founder", "Fractional CFO", "FP&A"],
    useCases: ["SME","Forecast","Liquidity"],
    level: "Starter",
    status: "Available",
    priority: "P1",
    horizon: "Twelve monthly forecast periods",
    setup: "20-40 minutes",
    tags: ["SME","Forecast","Liquidity"],
    compatibility: "Excel 365",
    version: "1.4.0",
    lastTested: "2026-08-17",
    qa: "10 / 10 calculation controls PASS; 5 / 5 sheets rendered",
    file: {
      path: "sme-integrated-forecast/model/tdat-sme-integrated-forecast.xlsx",
      size: "22.3 KB",
      format: ".xlsx",
      macros: false,
      externalLinks: false,
      circularReferences: false,
      sha256: "48120A58619DA52FE28309ACFFD740B237423879D48CD49FED32E5341DAACCC9",
    },
  },
  {
    id: "TDAT-FM-CORE-002",
    slug: "multi-entity-consolidation-fx",
    title: "Multi-Entity Consolidation & FX",
    decision: "How do entity growth, intercompany eliminations, and FX translation shape consolidated performance?",
    description: "Parent and subsidiary operating schedules. Five-year FX translation ramp and intercompany eliminations. Reported-versus-constant-FX EBITDA bridge",
    domain: "Core Statements",
    roles: ["Regional Finance", "Controllership", "FP&A", "Accounting"],
    useCases: ["Consolidation","FX","Multi-entity"],
    level: "Starter",
    status: "Available",
    priority: "P2",
    horizon: "Base plus five forecast years",
    setup: "20-40 minutes",
    tags: ["Consolidation","FX","Multi-entity"],
    compatibility: "Excel 365",
    version: "1.4.0",
    lastTested: "2026-08-17",
    qa: "10 / 10 calculation controls PASS; 5 / 5 sheets rendered",
    file: {
      path: "multi-entity-consolidation-fx/model/tdat-multi-entity-consolidation-fx.xlsx",
      size: "19.0 KB",
      format: ".xlsx",
      macros: false,
      externalLinks: false,
      circularReferences: false,
      sha256: "37342140615653CA104D47818ED43E896B8C015228246AB375B7CEC90614CD51",
    },
  },
  {
    id: "TDAT-FM-PE-001",
    slug: "lbo-returns-model",
    title: "LBO Returns Model",
    decision: "How do EBITDA growth, cash conversion, debt paydown, and exit assumptions drive sponsor returns?",
    description: "Entry sources and uses with sponsor equity plug. Five-year EBITDA, cash generation, and cash-sweep debt schedule. Hold-period exit bridge, sponsor cash flows, MOIC, and IRR",
    domain: "Valuation & Transactions",
    roles: ["Private Equity", "Investment Banking", "Leveraged Finance"],
    useCases: ["LBO","Debt paydown","Sponsor returns"],
    level: "Starter",
    status: "Available",
    priority: "P2",
    horizon: "Entry plus five forecast years",
    setup: "20-40 minutes",
    tags: ["LBO","Debt paydown","Sponsor returns"],
    compatibility: "Excel 365",
    version: "1.4.0",
    lastTested: "2026-08-17",
    qa: "10 / 10 calculation controls PASS; 5 / 5 sheets rendered",
    file: {
      path: "lbo-returns-model/model/tdat-lbo-returns-model.xlsx",
      size: "19.9 KB",
      format: ".xlsx",
      macros: false,
      externalLinks: false,
      circularReferences: false,
      sha256: "B0F17C67C7047F44E5F87A5A81685245034E341C0FE5CB8C6718181331AEC612",
    },
  },
  {
    id: "TDAT-FM-TSY-003",
    slug: "fx-exposure-hedge",
    title: "FX Exposure & Hedge",
    decision: "How much FX loss remains after one forward hedge?",
    description: "One net foreign-currency exposure. One forward hedge and five visible spot scenarios. Selected-case bridge plus loss and protection attribution",
    domain: "Treasury & Capital",
    roles: ["Treasury", "Enterprise Risk", "Corporate Finance"],
    useCases: ["FX risk","Hedge coverage","Treasury"],
    level: "Starter",
    status: "Available",
    priority: "P2",
    horizon: "Five spot scenarios / one settlement",
    setup: "20-40 minutes",
    tags: ["FX risk","Hedge coverage","Treasury"],
    compatibility: "Excel 365",
    version: "1.4.0",
    lastTested: "2026-08-17",
    qa: "10 / 10 calculation controls PASS; 5 / 5 sheets rendered",
    file: {
      path: "fx-exposure-hedge/model/tdat-fx-exposure-hedge.xlsx",
      size: "16.6 KB",
      format: ".xlsx",
      macros: false,
      externalLinks: false,
      circularReferences: false,
      sha256: "593BCC1DF75F44EC6DA8DC436FE2A192DABE246EB4191526B70EF7EEECFC0E5B",
    },
  },
  {
    id: "TDAT-FM-RSK-002",
    slug: "ecl-credit-stress-lite",
    title: "ECL Credit Stress Lite",
    decision: "What loss allowance results for one portfolio under stress?",
    description: "One portfolio exposure at default. Stage-based PD with one stress multiplier. Selected-case bridge plus visible Stage 1 / 2 / 3 comparison",
    domain: "Credit & Risk",
    roles: ["Credit Risk", "Banking Finance", "Risk Analytics", "Financial Reporting"],
    useCases: ["Credit risk","Expected loss","Stress"],
    level: "Starter",
    status: "Available",
    priority: "P2",
    horizon: "12-month / lifetime",
    setup: "20-40 minutes",
    tags: ["Credit risk","Expected loss","Stress"],
    compatibility: "Excel 365",
    version: "1.4.0",
    lastTested: "2026-08-17",
    qa: "10 / 10 calculation controls PASS; 5 / 5 sheets rendered",
    file: {
      path: "ecl-credit-stress-lite/model/tdat-ecl-credit-stress-lite.xlsx",
      size: "17.3 KB",
      format: ".xlsx",
      macros: false,
      externalLinks: false,
      circularReferences: false,
      sha256: "47570285321298C10B65120675EF5F26AC5ACDC317BA8032BF319D6D2DB5AF7F",
    },
  },
  {
    id: "TDAT-FM-RSK-003",
    slug: "market-portfolio-stress",
    title: "Market Risk / Portfolio Stress",
    decision: "How much could a three-asset portfolio lose under direct shocks?",
    description: "Three asset buckets and direct price shocks. Four-line asset and liquidity loss attribution. Stress and concentration limit headroom",
    domain: "Credit & Risk",
    roles: ["Market Risk", "Portfolio Risk", "Investment Analyst"],
    useCases: ["Market risk","Stress loss","Concentration"],
    level: "Starter",
    status: "Available",
    priority: "P2",
    horizon: "One stress date",
    setup: "20-40 minutes",
    tags: ["Market risk","Stress loss","Concentration"],
    compatibility: "Excel 365",
    version: "1.4.0",
    lastTested: "2026-08-17",
    qa: "10 / 10 calculation controls PASS; 5 / 5 sheets rendered",
    file: {
      path: "market-portfolio-stress/model/tdat-market-portfolio-stress.xlsx",
      size: "16.8 KB",
      format: ".xlsx",
      macros: false,
      externalLinks: false,
      circularReferences: false,
      sha256: "F2920A3A5C0572A1F42879B686D5B1B91F0ED4F552D56B88D0ABE88AF629697D",
    },
  },
  {
    id: "TDAT-FM-PF-002",
    slug: "debt-sculpting-waterfall",
    title: "Debt Sculpting & Waterfall",
    decision: "Can projected cash repay one term loan at the target DSCR?",
    description: "Ten-year CFADS generated from two inputs. Target-DSCR principal sculpting. Debt capacity, balloon, and cash to equity",
    domain: "Project & Real Assets",
    roles: ["Project Finance", "Infrastructure Finance", "Structured Finance"],
    useCases: ["Debt capacity","DSCR","Cash waterfall"],
    level: "Starter",
    status: "Available",
    priority: "P2",
    horizon: "Up to 10 years",
    setup: "20-40 minutes",
    tags: ["Debt capacity","DSCR","Cash waterfall"],
    compatibility: "Excel 365",
    version: "1.4.0",
    lastTested: "2026-08-17",
    qa: "10 / 10 calculation controls PASS; 5 / 5 sheets rendered",
    file: {
      path: "debt-sculpting-waterfall/model/tdat-debt-sculpting-waterfall.xlsx",
      size: "19.1 KB",
      format: ".xlsx",
      macros: false,
      externalLinks: false,
      circularReferences: false,
      sha256: "914A1C000343ACC0E808B2ABE1B61E4ED5996ACD93E312E2359ED84C3F6FE86C",
    },
  },
  {
    id: "TDAT-FM-PER-001",
    slug: "personal-budget-net-worth",
    title: "Personal Budget & Net Worth",
    decision: "After one year, am I spending within income and building net worth?",
    description: "One monthly income and two spending totals. Twelve-month debt, cash, and investment roll-forward. Ending net worth and emergency-cash view",
    domain: "Personal Finance",
    roles: ["Individual / Household", "Financial Education / Learner"],
    useCases: ["Budget","Debt payoff","Net worth"],
    level: "Starter",
    status: "Available",
    priority: "P2",
    horizon: "12 months",
    setup: "20-40 minutes",
    tags: ["Budget","Debt payoff","Net worth"],
    compatibility: "Excel 365",
    version: "1.4.0",
    lastTested: "2026-08-17",
    qa: "10 / 10 calculation controls PASS; 5 / 5 sheets rendered",
    file: {
      path: "personal-budget-net-worth/model/tdat-personal-budget-net-worth.xlsx",
      size: "19.1 KB",
      format: ".xlsx",
      macros: false,
      externalLinks: false,
      circularReferences: false,
      sha256: "FC79452D2EE3AB18FE923C6F6FDE6C0D84A43398C6576622928AC8B295D0EF47",
    },
  },
  {
    id: "TDAT-FM-PER-002",
    slug: "retirement-scenario-planner",
    title: "Retirement Scenario Planner",
    decision: "Will savings support the planned withdrawal through the plan age?",
    description: "One deterministic real-return path. Contributions before retirement and a level net withdrawal. Funding bridge plus seven visible age milestones",
    domain: "Personal Finance",
    roles: ["Individual / Household", "Financial Education / Learner"],
    useCases: ["Retirement","Savings","Drawdown"],
    level: "Starter",
    status: "Available",
    priority: "P2",
    horizon: "Up to 60 years",
    setup: "20-40 minutes",
    tags: ["Retirement","Savings","Drawdown"],
    compatibility: "Excel 365",
    version: "1.4.0",
    lastTested: "2026-08-17",
    qa: "10 / 10 calculation controls PASS; 5 / 5 sheets rendered",
    file: {
      path: "retirement-scenario-planner/model/tdat-retirement-scenario-planner.xlsx",
      size: "17.8 KB",
      format: ".xlsx",
      macros: false,
      externalLinks: false,
      circularReferences: false,
      sha256: "D68139BD39227F730B2ADB185D00E7FF94E57B69641831646F48275D646DA5A5",
    },
  },
  {
    id: "TDAT-FM-COM-001",
    slug: "pricing-margin-waterfall",
    title: "Pricing & Margin Waterfall",
    decision: "Will one price change improve contribution after volume and cost effects?",
    description: "One current offer and one proposed offer. Direct volume response and unit-cost change. Contribution uplift, break-even volume, and a visible driver waterfall",
    domain: "Planning & Performance",
    roles: ["Commercial Finance", "FP&A", "Pricing Finance", "Sales Finance"],
    useCases: ["Pricing","Margin","Contribution"],
    level: "Starter",
    status: "Available",
    priority: "P2",
    horizon: "One current vs proposed case",
    setup: "20-40 minutes",
    tags: ["Pricing","Margin","Contribution"],
    compatibility: "Excel 365",
    version: "1.4.0",
    lastTested: "2026-08-17",
    qa: "10 / 10 calculation controls PASS; 5 / 5 sheets rendered",
    file: {
      path: "pricing-margin-waterfall/model/tdat-pricing-margin-waterfall.xlsx",
      size: "17.1 KB",
      format: ".xlsx",
      macros: false,
      externalLinks: false,
      circularReferences: false,
      sha256: "0C6660D75A0125414656E225925C2EAD3BF6A77599844BB71089921309ACEAC0",
    },
  },
  {
    id: "TDAT-FM-SME-002",
    slug: "saas-unit-economics",
    title: "SaaS Unit Economics",
    decision: "Does a steady growth plan create efficient ARR without using too much cash?",
    description: "One steady twelve-month customer plan. ARR, CAC, LTV/CAC, payback, and burn. Monthly MRR, ARR, EBITDA, and cash roll-forward plus an annual bridge",
    domain: "SME & Startup",
    roles: ["Startup Finance", "FP&A", "Venture Capital", "Founder"],
    useCases: ["ARR","Unit economics","Cash runway"],
    level: "Starter",
    status: "Available",
    priority: "P2",
    horizon: "12 months",
    setup: "20-40 minutes",
    tags: ["ARR","Unit economics","Cash runway"],
    compatibility: "Excel 365",
    version: "1.4.0",
    lastTested: "2026-08-17",
    qa: "10 / 10 calculation controls PASS; 5 / 5 sheets rendered",
    file: {
      path: "saas-unit-economics/model/tdat-saas-unit-economics.xlsx",
      size: "19.3 KB",
      format: ".xlsx",
      macros: false,
      externalLinks: false,
      circularReferences: false,
      sha256: "1818513A46A31775EE26404EB63019D241C19E17FDCB3E01C65A436B9B255F69",
    },
  },
];
