window.TDAT_ROLE_FAMILIES = [
  {
    id: "corporate-finance-fpa",
    label: "Corporate Finance & FP&A",
    roles: ["CFO Office", "Corporate Finance", "Financial Reporting", "Finance Business Partner", "FP&A", "Fractional CFO", "Regional Finance"],
  },
  {
    id: "commercial-operational-finance",
    label: "Commercial & Operational Finance",
    roles: ["Commercial Finance", "HR Finance", "Operations Finance", "Pricing Finance", "Sales Finance"],
  },
  {
    id: "accounting-controllership",
    label: "Accounting & Controllership",
    roles: ["Accounting", "Controllership"],
  },
  {
    id: "investment-valuation-transactions",
    label: "Investment, Valuation & Transactions",
    roles: ["Corporate Development", "Equity Research", "Investment Analyst", "Investment Banking", "Leveraged Finance", "M&A Advisory", "Private Equity", "Valuation Advisory", "Venture Capital"],
  },
  {
    id: "treasury-funding-real-assets",
    label: "Treasury, Funding & Real Assets",
    roles: ["Infrastructure Finance", "Project Finance", "Structured Finance", "Treasury"],
  },
  {
    id: "banking-credit-risk",
    label: "Banking, Credit & Risk",
    roles: ["Banking Finance", "Commercial Banking", "Credit Analysis", "Credit Risk", "Enterprise Risk", "Lending", "Market Risk", "Portfolio Risk", "Risk Analytics"],
  },
  {
    id: "sme-startup-personal-finance",
    label: "SME, Startup & Personal Finance",
    roles: ["Financial Education / Learner", "Founder", "Individual / Household", "SME Finance", "Startup Finance"],
  },
];

window.TDAT_MODEL_LIBRARY = [
  {
    id: "TDAT-FM-CORE-001",
    slug: "three-statement-model",
    title: "Three-Statement Model Starter",
    decision: "How do operating assumptions flow through profit, financial position, cash, debt, and retained earnings?",
    description: "An integrated single-entity operating model with three historical years, five forecast years, visible schedules, three scenarios, and a central checks sheet.",
    domain: "Core Statements",
    roles: ["FP&A", "Corporate Finance", "Accounting", "Valuation Advisory"],
    useCases: ["Integrated forecast", "Cash planning", "Valuation foundation", "Interview case"],
    level: "Practitioner",
    status: "Available",
    priority: "P0",
    horizon: "3A + 5F annual",
    setup: "2–4 hours",
    compatibility: "Excel 365",
    tags: ["P&L", "Balance Sheet", "Cash Flow", "Scenarios", "Checks"],
    version: "1.0.0",
    lastTested: "2026-07-13",
    qa: "27 / 27 published checks PASS",
    file: {
      path: "three-statement-model/model/tdat-three-statement-model.xlsx",
      size: "44.3 KB",
      format: ".xlsx",
      macros: false,
      externalLinks: false,
      circularReferences: false,
      sha256: "720A4BEC9679F3A72F96DECC37FF9F08EF871DB3C07A41350DB59620AF6CF333",
    },
  },
  {
    id: "TDAT-FM-FPA-001",
    slug: "budget-rolling-forecast",
    title: "Budget & Rolling Forecast",
    decision: "What changed in the outlook, why, and what must management do next?",
    description: "Driver-based planning with actual, budget, forecast, prior-year, scenario, and forecast-accuracy views.",
    domain: "Planning & Performance",
    roles: ["FP&A", "Finance Business Partner", "Corporate Finance"],
    useCases: ["Budget", "Reforecast", "Long-range plan"],
    level: "Practitioner",
    status: "Roadmap",
    priority: "P0",
    horizon: "12–36 months",
    setup: "1–3 hours",
    tags: ["Budget", "Forecast", "Drivers", "Variance"],
  },
  {
    id: "TDAT-FM-TSY-001",
    slug: "thirteen-week-cash-flow",
    title: "13-Week Cash Flow",
    decision: "When does liquidity tighten, and which payment or funding action comes first?",
    description: "A weekly direct cash forecast with receipts, disbursements, minimum cash, runway, and funding-gap visibility.",
    domain: "Treasury & Capital",
    roles: ["Treasury", "FP&A", "CFO Office", "SME Finance"],
    useCases: ["Liquidity", "Payment sequencing", "Cash runway"],
    level: "Starter",
    status: "Roadmap",
    priority: "P0",
    horizon: "13 weeks",
    setup: "30–60 minutes",
    tags: ["Cash", "Liquidity", "Runway", "Weekly"],
  },
  {
    id: "TDAT-FM-VAL-001",
    slug: "dcf-valuation",
    title: "DCF Valuation",
    decision: "What enterprise and equity value range is supported by operating cash flow and risk assumptions?",
    description: "Unlevered free cash flow, WACC, terminal value, equity bridge, and two-way sensitivity logic.",
    domain: "Valuation & Transactions",
    roles: ["Valuation Advisory", "Corporate Development", "Equity Research", "Investment Banking"],
    useCases: ["Enterprise value", "Equity value", "Sensitivity"],
    level: "Practitioner",
    status: "Roadmap",
    priority: "P0",
    horizon: "5–10 years",
    setup: "1–2 hours",
    tags: ["DCF", "WACC", "Terminal Value", "Sensitivity"],
  },
  {
    id: "TDAT-FM-INV-001",
    slug: "capex-business-case",
    title: "Capex / Business Case",
    decision: "Should management approve, defer, resize, or reject the investment?",
    description: "Incremental cash flow, NPV, IRR, payback, scenario, and implementation-risk framework.",
    domain: "Investment & Portfolio",
    roles: ["FP&A", "Corporate Finance", "Investment Analyst", "Operations Finance"],
    useCases: ["Investment approval", "NPV", "Payback"],
    level: "Starter",
    status: "Roadmap",
    priority: "P0",
    horizon: "3–15 years",
    setup: "30–60 minutes",
    tags: ["Capex", "NPV", "IRR", "Decision"],
  },
  {
    id: "TDAT-FM-FPA-002",
    slug: "working-capital-planner",
    title: "Working Capital Planner",
    decision: "How much cash can be released through DSO, DIO, and DPO actions?",
    description: "Receivables, inventory, payables, cash conversion cycle, owner actions, and cash-release scenarios.",
    domain: "Planning & Performance",
    roles: ["FP&A", "Treasury", "Commercial Finance", "Accounting"],
    useCases: ["DSO", "DIO", "DPO", "Cash release"],
    level: "Starter",
    status: "Roadmap",
    priority: "P1",
    horizon: "12–36 months",
    setup: "30–90 minutes",
    tags: ["Working Capital", "Cash", "Collections"],
  },
  {
    id: "TDAT-FM-FPA-003",
    slug: "variance-bridge-forecast-accuracy",
    title: "Variance Bridge & Forecast Accuracy",
    decision: "Which drivers explain the gap, who owns them, and how reliable is the forecast?",
    description: "Actual versus budget, prior year, and forecast with price-volume-mix logic and owner/action tracking.",
    domain: "Planning & Performance",
    roles: ["FP&A", "Commercial Finance", "Finance Business Partner"],
    useCases: ["Variance", "Bridge", "Forecast accuracy"],
    level: "Starter",
    status: "Roadmap",
    priority: "P1",
    horizon: "Monthly / QTD / YTD",
    setup: "30–60 minutes",
    tags: ["Variance", "Price Volume Mix", "Owner", "Action"],
  },
  {
    id: "TDAT-FM-FPA-004",
    slug: "headcount-compensation-plan",
    title: "Headcount & Compensation Plan",
    decision: "What hiring plan balances capacity, cost, timing, and productivity?",
    description: "Opening headcount, hires, exits, start dates, compensation, benefits, vacancies, and scenario controls.",
    domain: "Planning & Performance",
    roles: ["FP&A", "HR Finance", "Finance Business Partner"],
    useCases: ["Workforce plan", "Personnel cost", "Capacity"],
    level: "Starter",
    status: "Roadmap",
    priority: "P1",
    horizon: "12–36 months",
    setup: "30–90 minutes",
    tags: ["Headcount", "Compensation", "Hiring"],
  },
  {
    id: "TDAT-FM-VAL-002",
    slug: "trading-comps",
    title: "Trading Comparables",
    decision: "How does the target trade against peers on growth, margins, and valuation multiples?",
    description: "Peer set, calendarization, enterprise value, key multiples, quartiles, and implied valuation range.",
    domain: "Valuation & Transactions",
    roles: ["Investment Banking", "Equity Research", "Corporate Development", "Valuation Advisory"],
    useCases: ["Relative valuation", "Peer benchmark"],
    level: "Practitioner",
    status: "Roadmap",
    priority: "P1",
    horizon: "LTM / NTM snapshot",
    setup: "1–2 hours",
    tags: ["Comps", "Multiples", "Peers"],
  },
  {
    id: "TDAT-FM-MA-001",
    slug: "ma-accretion-dilution",
    title: "M&A Accretion / Dilution",
    decision: "Does the transaction create or dilute earnings, and which funding or synergy assumptions matter most?",
    description: "Purchase price, funding mix, transaction adjustments, synergies, new share count, and EPS impact.",
    domain: "Valuation & Transactions",
    roles: ["Investment Banking", "M&A Advisory", "Corporate Development"],
    useCases: ["Deal impact", "Funding mix", "Synergies"],
    level: "Advanced",
    status: "Roadmap",
    priority: "P1",
    horizon: "3–5 years",
    setup: "2–4 hours",
    tags: ["M&A", "Accretion", "Dilution", "Synergy"],
  },
  {
    id: "TDAT-FM-TSY-002",
    slug: "debt-covenant-model",
    title: "Debt & Covenant Model",
    decision: "Can the business service debt and preserve covenant headroom under downside conditions?",
    description: "Debt roll-forward, cash interest, amortization, leverage, coverage, covenant, and maturity views.",
    domain: "Treasury & Capital",
    roles: ["Treasury", "Corporate Finance", "Credit Analysis", "FP&A"],
    useCases: ["Debt service", "Covenants", "Refinancing"],
    level: "Practitioner",
    status: "Roadmap",
    priority: "P1",
    horizon: "3–10 years",
    setup: "1–2 hours",
    tags: ["Debt", "Interest", "Covenants", "Headroom"],
  },
  {
    id: "TDAT-FM-RSK-001",
    slug: "credit-underwriting-dscr",
    title: "Credit Underwriting / DSCR",
    decision: "Can the borrower afford the facility across base and stressed cash flows?",
    description: "Borrower cash flow, leverage, DSCR, debt capacity, downside, collateral, and exception tracking.",
    domain: "Credit & Risk",
    roles: ["Credit Analysis", "Enterprise Risk", "Commercial Banking", "Lending"],
    useCases: ["Underwriting", "DSCR", "Debt capacity"],
    level: "Practitioner",
    status: "Roadmap",
    priority: "P1",
    horizon: "1–5 years",
    setup: "1–2 hours",
    tags: ["Credit", "DSCR", "Leverage", "Stress"],
  },
  {
    id: "TDAT-FM-PF-001",
    slug: "project-finance-lite",
    title: "Project Finance Lite",
    decision: "Is the project bankable, and how do funding, construction, and operating assumptions affect returns?",
    description: "Construction draw, operating cash flow, debt service, DSCR, project IRR, equity IRR, and funding gap.",
    domain: "Project & Real Assets",
    roles: ["Project Finance", "Infrastructure Finance", "Lending", "Investment Analyst"],
    useCases: ["Bankability", "Project returns", "Funding"],
    level: "Advanced",
    status: "Roadmap",
    priority: "P1",
    horizon: "Construction + 10–25 years",
    setup: "3–6 hours",
    tags: ["Project Finance", "DSCR", "IRR", "Construction"],
  },
  {
    id: "TDAT-FM-SME-001",
    slug: "sme-integrated-forecast",
    title: "SME Integrated Forecast",
    decision: "How long can the business operate, when does it break even, and what funding is required?",
    description: "Sales, margin, payroll, working capital, 13-week cash, 24-month forecast, and funding runway.",
    domain: "SME & Startup",
    roles: ["SME Finance", "Founder", "Fractional CFO", "FP&A"],
    useCases: ["Runway", "Break-even", "Funding"],
    level: "Starter",
    status: "Roadmap",
    priority: "P1",
    horizon: "13 weeks + 24 months",
    setup: "1–2 hours",
    tags: ["SME", "Runway", "Break-even", "Cash"],
  },
  {
    id: "TDAT-FM-CORE-002",
    slug: "multi-entity-consolidation-fx",
    title: "Multi-Entity Consolidation & FX",
    decision: "What is the consolidated result after currency translation, eliminations, and entity-level review?",
    description: "Entity inputs, FX translation, eliminations, ownership, consolidated statements, and reconciliation controls.",
    domain: "Core Statements",
    roles: ["Regional Finance", "Controllership", "FP&A", "Accounting"],
    useCases: ["Consolidation", "FX translation", "Eliminations"],
    level: "Advanced",
    status: "Roadmap",
    priority: "P2",
    horizon: "12–60 months",
    setup: "3–6 hours",
    tags: ["Consolidation", "FX", "Eliminations", "Multi-entity"],
  },
  {
    id: "TDAT-FM-PE-001",
    slug: "lbo-returns-model",
    title: "LBO Returns Model",
    decision: "What leverage, operating improvement, cash sweep, and exit assumptions support sponsor returns?",
    description: "Sources and uses, debt tranches, cash sweep, exit bridge, IRR, MOIC, and downside sensitivities.",
    domain: "Valuation & Transactions",
    roles: ["Private Equity", "Investment Banking", "Leveraged Finance"],
    useCases: ["Sponsor returns", "Leverage", "Exit"],
    level: "Advanced",
    status: "Roadmap",
    priority: "P2",
    horizon: "5–7 years",
    setup: "2–4 hours",
    tags: ["LBO", "IRR", "MOIC", "Cash Sweep"],
  },
  {
    id: "TDAT-FM-TSY-003",
    slug: "fx-exposure-hedge",
    title: "FX Exposure & Hedge",
    decision: "Which currency exposures matter, how much is hedged, and what remains under rate shocks?",
    description: "Transaction exposures, hedge coverage, maturity profile, rate sensitivity, and residual P&L/cash risk.",
    domain: "Treasury & Capital",
    roles: ["Treasury", "Enterprise Risk", "Corporate Finance"],
    useCases: ["FX exposure", "Hedge coverage", "Sensitivity"],
    level: "Practitioner",
    status: "Roadmap",
    priority: "P2",
    horizon: "1–24 months",
    setup: "30–90 minutes",
    tags: ["FX", "Hedging", "Treasury", "Sensitivity"],
  },
  {
    id: "TDAT-FM-RSK-002",
    slug: "ecl-credit-stress-lite",
    title: "ECL / Credit Stress Lite",
    decision: "How do PD, LGD, EAD, staging, and macro scenarios change expected loss?",
    description: "Illustrative expected-credit-loss engine with transparent assumptions, scenario weights, and reconciliation checks.",
    domain: "Credit & Risk",
    roles: ["Credit Risk", "Banking Finance", "Risk Analytics", "Financial Reporting"],
    useCases: ["Expected loss", "Stress", "Provision"],
    level: "Advanced",
    status: "Roadmap",
    priority: "P2",
    horizon: "12-month / lifetime",
    setup: "2–4 hours",
    tags: ["ECL", "PD", "LGD", "EAD"],
  },
  {
    id: "TDAT-FM-RSK-003",
    slug: "market-portfolio-stress",
    title: "Market Risk / Portfolio Stress",
    decision: "Where do shocks, concentration, and correlations create the largest downside exposure?",
    description: "Scenario shocks, position mapping, concentration, loss attribution, and illustrative risk-limit monitoring.",
    domain: "Credit & Risk",
    roles: ["Market Risk", "Portfolio Risk", "Investment Analyst"],
    useCases: ["Stress testing", "Concentration", "Limits"],
    level: "Advanced",
    status: "Roadmap",
    priority: "P2",
    horizon: "Daily to annual",
    setup: "2–4 hours",
    tags: ["Market Risk", "Stress", "Concentration"],
  },
  {
    id: "TDAT-FM-PF-002",
    slug: "debt-sculpting-waterfall",
    title: "Debt Sculpting & Waterfall",
    decision: "What repayment profile and cash waterfall meet coverage constraints while preserving equity value?",
    description: "DSCR-driven sculpting, reserve accounts, waterfall priorities, distributions, and lender/equity returns.",
    domain: "Project & Real Assets",
    roles: ["Project Finance", "Infrastructure Finance", "Structured Finance"],
    useCases: ["Debt sculpting", "Cash waterfall", "Coverage"],
    level: "Advanced",
    status: "Roadmap",
    priority: "P2",
    horizon: "10–30 years",
    setup: "4–8 hours",
    tags: ["Sculpting", "Waterfall", "DSCR", "Reserves"],
  },
  {
    id: "TDAT-FM-PER-001",
    slug: "personal-budget-net-worth",
    title: "Personal Budget & Net Worth",
    decision: "How should income, spending, debt, savings, and goals be balanced over time?",
    description: "Monthly cash flow, net worth, debt payoff, emergency fund, and goal-tracking template for educational use.",
    domain: "Personal Finance",
    roles: ["Individual / Household", "Financial Education / Learner"],
    useCases: ["Budget", "Net worth", "Debt payoff"],
    level: "Starter",
    status: "Roadmap",
    priority: "P2",
    horizon: "Monthly + 10 years",
    setup: "30–60 minutes",
    tags: ["Personal Finance", "Budget", "Net Worth"],
  },
  {
    id: "TDAT-FM-PER-002",
    slug: "retirement-scenario-planner",
    title: "Retirement Scenario Planner",
    decision: "How do contributions, inflation, returns, timing, and drawdown assumptions affect retirement readiness?",
    description: "Educational contribution, accumulation, inflation, withdrawal, and sensitivity model with clear limitations.",
    domain: "Personal Finance",
    roles: ["Individual / Household", "Financial Education / Learner"],
    useCases: ["Retirement", "Contributions", "Drawdown"],
    level: "Practitioner",
    status: "Roadmap",
    priority: "P2",
    horizon: "20–40 years",
    setup: "45–90 minutes",
    tags: ["Retirement", "Inflation", "Scenario"],
  },
  {
    id: "TDAT-FM-COM-001",
    slug: "pricing-margin-waterfall",
    title: "Pricing & Margin Waterfall",
    decision: "Which customer, product, price, discount, mix, and cost actions protect contribution margin?",
    description: "List-to-net pricing, rebates, price-volume-mix, unit economics, customer profitability, and action list.",
    domain: "Planning & Performance",
    roles: ["Commercial Finance", "FP&A", "Pricing Finance", "Sales Finance"],
    useCases: ["Pricing", "Margin", "Customer profitability"],
    level: "Practitioner",
    status: "Roadmap",
    priority: "P2",
    horizon: "Monthly / annual",
    setup: "1–2 hours",
    tags: ["Pricing", "Margin", "Mix", "Profitability"],
  },
  {
    id: "TDAT-FM-SME-002",
    slug: "saas-unit-economics",
    title: "SaaS Unit Economics",
    decision: "Is growth efficient enough when retention, CAC, LTV, burn, and payback are viewed together?",
    description: "ARR bridge, cohort retention, CAC, LTV, gross margin, burn multiple, runway, and scenario logic.",
    domain: "SME & Startup",
    roles: ["Startup Finance", "FP&A", "Venture Capital", "Founder"],
    useCases: ["Unit economics", "Runway", "Fundraising"],
    level: "Practitioner",
    status: "Roadmap",
    priority: "P2",
    horizon: "24–60 months",
    setup: "1–2 hours",
    tags: ["SaaS", "ARR", "LTV", "CAC"],
  },
];
