window.TDAT_ROLE_FAMILIES = [
  {
    id: "corporate-finance-fpa",
    label: "Corporate Finance & FP&A",
    roles: ["CFO Office", "Corporate Finance", "Financial Reporting", "Finance Business Partner", "FP&A", "Fractional CFO", "Regional Finance"],
  },
  {
    id: "commercial-operational-finance",
    label: "Commercial & Operational Finance",
    roles: ["Commercial Finance", "HR Finance", "Operations Finance", "Pricing Finance", "Sales Finance"],
  },
  {
    id: "accounting-controllership",
    label: "Accounting & Controllership",
    roles: ["Accounting", "Controllership"],
  },
  {
    id: "investment-valuation-transactions",
    label: "Investment, Valuation & Transactions",
    roles: ["Corporate Development", "Equity Research", "Investment Analyst", "Investment Banking", "Leveraged Finance", "M&A Advisory", "Private Equity", "Valuation Advisory", "Venture Capital"],
  },
  {
    id: "treasury-funding-real-assets",
    label: "Treasury, Funding & Real Assets",
    roles: ["Infrastructure Finance", "Project Finance", "Structured Finance", "Treasury"],
  },
  {
    id: "banking-credit-risk",
    label: "Banking, Credit & Risk",
    roles: ["Banking Finance", "Commercial Banking", "Credit Analysis", "Credit Risk", "Enterprise Risk", "Lending", "Market Risk", "Portfolio Risk", "Risk Analytics"],
  },
  {
    id: "sme-startup-personal-finance",
    label: "SME, Startup & Personal Finance",
    roles: ["Financial Education / Learner", "Founder", "Individual / Household", "SME Finance", "Startup Finance"],
  },
];

window.TDAT_MODEL_LIBRARY = [
  {
    id: "TDAT-FM-CORE-001",
    slug: "three-statement-model",
    title: "Three-Statement Model Starter",
    decision: "How do operating assumptions flow through profit, financial position, cash, debt, and retained earnings?",
    description: "An integrated single-entity operating model with three historical years, five forecast years, visible schedules, three scenarios, and a central checks sheet.",
    domain: "Core Statements",
    roles: ["FP&A", "Corporate Finance", "Accounting", "Valuation Advisory"],
    useCases: ["Integrated forecast", "Cash planning", "Valuation foundation", "Interview case"],
    level: "Practitioner",
    status: "Available",
    priority: "P0",
    horizon: "3A + 5F annual",
    setup: "2–4 hours",
    compatibility: "Excel 365",
    tags: ["P&L", "Balance Sheet", "Cash Flow", "Scenarios", "Checks"],
    version: "1.0.0",
    lastTested: "2026-07-13",
    qa: "27 / 27 published checks PASS",
    file: {
      path: "three-statement-model/model/tdat-three-statement-model.xlsx",
      size: "44.3 KB",
      format: ".xlsx",
      macros: false,
      externalLinks: false,
      circularReferences: false,
      sha256: "720A4BEC9679F3A72F96DECC37FF9F08EF871DB3C07A41350DB59620AF6CF333",
    },
  },
  {
    id: "TDAT-FM-FPA-001",
    slug: "budget-rolling-forecast",
    title: "Budget & Rolling Forecast",
    decision: "What changed in the outlook, why, and what must management do next?",
    description: "Driver-based planning with actual, budget, forecast, prior-year, scenario, and forecast-accuracy views.",
    domain: "Planning & Performance",
    roles: ["FP&A", "Finance Business Partner", "Corporate Finance"],
    useCases: ["Budget", "Reforecast", "Long-range plan"],
    level: "Practitioner",
    status: "Available",
    priority: "P0",
    horizon: "12–36 months",
    setup: "1–3 hours",
    tags: ["Budget", "Forecast", "Drivers", "Variance"],
    compatibility: "Excel 365",
    version: "1.0.0",
    lastTested: "2026-07-13",
    qa: "11 / 11 published checks PASS; 9 / 9 sheets rendered",
    file: {
      path: "budget-rolling-forecast/model/tdat-budget-rolling-forecast.xlsx",
      size: "32.6 KB",
      format: ".xlsx",
      macros: false,
      externalLinks: false,
      circularReferences: false,
      sha256: "27E271FE9BB000D477610C307CB9E9A438ADB0AC536FE39D47B46B4920AA6E9F",
    },
  },
  {
    id: "TDAT-FM-TSY-001",
    slug: "thirteen-week-cash-flow",
    title: "13-Week Cash Flow",
    decision: "When does liquidity tighten, and which payment or funding action comes first?",
    description: "A weekly direct cash forecast with receipts, disbursements, minimum cash, runway, and funding-gap visibility.",
    domain: "Treasury & Capital",
    roles: ["Treasury", "FP&A", "CFO Office", "SME Finance"],
    useCases: ["Liquidity", "Payment sequencing", "Cash runway"],
    level: "Starter",
    status: "Available",
    priority: "P0",
    horizon: "13 weeks",
    setup: "30–60 minutes",
    tags: ["Cash", "Liquidity", "Runway", "Weekly"],
    compatibility: "Excel 365",
    version: "1.0.0",
    lastTested: "2026-07-13",
    qa: "10 / 10 published checks PASS; 9 / 9 sheets rendered",
    file: {
      path: "thirteen-week-cash-flow/model/tdat-thirteen-week-cash-flow.xlsx",
      size: "31.9 KB",
      format: ".xlsx",
      macros: false,
      externalLinks: false,
      circularReferences: false,
      sha256: "EB27DA86F271F642F45A7515635E61C54AA99DC6C34DC433E8DD0DB3C9504579",
    },
  },
  {
    id: "TDAT-FM-VAL-001",
    slug: "dcf-valuation",
    title: "DCF Valuation",
    decision: "What enterprise and equity value range is supported by operating cash flow and risk assumptions?",
    description: "Unlevered free cash flow, WACC, terminal value, equity bridge, and two-way sensitivity logic.",
    domain: "Valuation & Transactions",
    roles: ["Valuation Advisory", "Corporate Development", "Equity Research", "Investment Banking"],
    useCases: ["Enterprise value", "Equity value", "Sensitivity"],
    level: "Practitioner",
    status: "Available",
    priority: "P0",
    horizon: "5–10 years",
    setup: "1–2 hours",
    tags: ["DCF", "WACC", "Terminal Value", "Sensitivity"],
    compatibility: "Excel 365",
    version: "1.0.0",
    lastTested: "2026-07-13",
    qa: "12 / 12 published checks PASS; 9 / 9 sheets rendered",
    file: {
      path: "dcf-valuation/model/tdat-dcf-valuation.xlsx",
      size: "31.5 KB",
      format: ".xlsx",
      macros: false,
      externalLinks: false,
      circularReferences: false,
      sha256: "64FF0BA891EEB88E9A39CA545B8E4BF01C1D7582CE8A6D4A28A92218EAC980DE",
    },
  },
  {
    id: "TDAT-FM-INV-001",
    slug: "capex-business-case",
    title: "Capex / Business Case",
    decision: "Should management approve, defer, resize, or reject the investment?",
    description: "Incremental cash flow, NPV, IRR, payback, scenario, and implementation-risk framework.",
    domain: "Investment & Portfolio",
    roles: ["FP&A", "Corporate Finance", "Investment Analyst", "Operations Finance"],
    useCases: ["Investment approval", "NPV", "Payback"],
    level: "Starter",
    status: "Available",
    priority: "P0",
    horizon: "3–15 years",
    setup: "30–60 minutes",
    tags: ["Capex", "NPV", "IRR", "Decision"],
    compatibility: "Excel 365",
    version: "1.0.0",
    lastTested: "2026-07-13",
    qa: "9 / 9 published checks PASS; 9 / 9 sheets rendered",
    file: {
      path: "capex-business-case/model/tdat-capex-business-case.xlsx",
      size: "32.5 KB",
      format: ".xlsx",
      macros: false,
      externalLinks: false,
      circularReferences: false,
      sha256: "9FD02ED84EEEC75B5EAA0BCE8EEA450CA347B1E0FB363C2A529FF2D440EF9929",
    },
  },
  {
    id: "TDAT-FM-FPA-002",
    slug: "working-capital-planner",
    title: "Working Capital Planner",
    decision: "How much cash can be released through DSO, DIO, and DPO actions?",
    description: "Receivables, inventory, payables, cash conversion cycle, owner actions, and cash-release scenarios.",
    domain: "Planning & Performance",
    roles: ["FP&A", "Treasury", "Commercial Finance", "Accounting"],
    useCases: ["DSO", "DIO", "DPO", "Cash release"],
    level: "Starter",
    status: "Available",
    priority: "P1",
    horizon: "12–36 months",
    setup: "30–90 minutes",
    tags: ["Working Capital", "Cash", "Collections"],
    compatibility: "Excel 365",
    version: "1.0.0",
    lastTested: "2026-07-13",
    qa: "11 / 11 published checks PASS; 9 / 9 sheets rendered",
    file: {
      path: "working-capital-planner/model/tdat-working-capital-planner.xlsx",
      size: "31.8 KB",
      format: ".xlsx",
      macros: false,
      externalLinks: false,
      circularReferences: false,
      sha256: "9691D035565443207DBDBADAC60A96A0B993978E051D8877ED660A5E339C9D35",
    },
  },
  {
    id: "TDAT-FM-FPA-003",
    slug: "variance-bridge-forecast-accuracy",
    title: "Variance Bridge & Forecast Accuracy",
    decision: "Which drivers explain the gap, who owns them, and how reliable is the forecast?",
    description: "Actual versus budget, prior year, and forecast with price-volume-mix logic and owner/action tracking.",
    domain: "Planning & Performance",
    roles: ["FP&A", "Commercial Finance", "Finance Business Partner"],
    useCases: ["Variance", "Bridge", "Forecast accuracy"],
    level: "Starter",
    status: "Available",
    priority: "P1",
    horizon: "Monthly / QTD / YTD",
    setup: "30–60 minutes",
    tags: ["Variance", "Price Volume Mix", "Owner", "Action"],
    compatibility: "Excel 365",
    version: "1.0.0",
    lastTested: "2026-07-13",
    qa: "9 / 9 published checks PASS; 9 / 9 sheets rendered",
    file: {
      path: "variance-bridge-forecast-accuracy/model/tdat-variance-bridge-forecast-accuracy.xlsx",
      size: "31.1 KB",
      format: ".xlsx",
      macros: false,
      externalLinks: false,
      circularReferences: false,
      sha256: "3DC480AD24396D89D12076131571554CEB6759969869C750B578A49041328459",
    },
  },
  {
    id: "TDAT-FM-FPA-004",
    slug: "headcount-compensation-plan",
    title: "Headcount & Compensation Plan",
    decision: "What hiring plan balances capacity, cost, timing, and productivity?",
    description: "Opening headcount, hires, exits, start dates, compensation, benefits, vacancies, and scenario controls.",
    domain: "Planning & Performance",
    roles: ["FP&A", "HR Finance", "Finance Business Partner"],
    useCases: ["Workforce plan", "Personnel cost", "Capacity"],
    level: "Starter",
    status: "Available",
    priority: "P1",
    horizon: "12–36 months",
    setup: "30–90 minutes",
    tags: ["Headcount", "Compensation", "Hiring"],
    compatibility: "Excel 365",
    version: "1.0.0",
    lastTested: "2026-07-13",
    qa: "9 / 9 published checks PASS; 9 / 9 sheets rendered",
    file: {
      path: "headcount-compensation-plan/model/tdat-headcount-compensation-plan.xlsx",
      size: "32.2 KB",
      format: ".xlsx",
      macros: false,
      externalLinks: false,
      circularReferences: false,
      sha256: "258D96AF9463447E08ADE9E1946380AB1C974CE43A1A59E9A362EF530B6102F0",
    },
  },
  {
    id: "TDAT-FM-VAL-002",
    slug: "trading-comps",
    title: "Trading Comparables",
    decision: "How does the target trade against peers on growth, margins, and valuation multiples?",
    description: "Peer set, calendarization, enterprise value, key multiples, quartiles, and implied valuation range.",
    domain: "Valuation & Transactions",
    roles: ["Investment Banking", "Equity Research", "Corporate Development", "Valuation Advisory"],
    useCases: ["Relative valuation", "Peer benchmark"],
    level: "Practitioner",
    status: "Available",
    priority: "P1",
    horizon: "LTM / NTM snapshot",
    setup: "1–2 hours",
    tags: ["Comps", "Multiples", "Peers"],
    compatibility: "Excel 365",
    version: "1.0.0",
    lastTested: "2026-07-13",
    qa: "11 / 11 published checks PASS; 9 / 9 sheets rendered",
    file: {
      path: "trading-comps/model/tdat-trading-comps.xlsx",
      size: "30.6 KB",
      format: ".xlsx",
      macros: false,
      externalLinks: false,
      circularReferences: false,
      sha256: "D7D473BBC52FFDB5F35F9A36FA61F1B2564352113F363C8CE01A1D3AFA0DD9CB",
    },
  },
  {
    id: "TDAT-FM-MA-001",
    slug: "ma-accretion-dilution",
    title: "M&A Accretion / Dilution",
    decision: "Does the transaction create or dilute earnings, and which funding or synergy assumptions matter most?",
    description: "Purchase price, funding mix, transaction adjustments, synergies, new share count, and EPS impact.",
    domain: "Valuation & Transactions",
    roles: ["Investment Banking", "M&A Advisory", "Corporate Development"],
    useCases: ["Deal impact", "Funding mix", "Synergies"],
    level: "Advanced",
    status: "Available",
    priority: "P1",
    horizon: "3–5 years",
    setup: "2–4 hours",
    tags: ["M&A", "Accretion", "Dilution", "Synergy"],
    compatibility: "Excel 365",
    version: "1.0.0",
    lastTested: "2026-07-13",
    qa: "9 / 9 published checks PASS; 9 / 9 sheets rendered",
    file: {
      path: "ma-accretion-dilution/model/tdat-ma-accretion-dilution.xlsx",
      size: "31.1 KB",
      format: ".xlsx",
      macros: false,
      externalLinks: false,
      circularReferences: false,
      sha256: "07281310A5FDA1F76713E9422961405B41A7CD24E152211DBA43CB4068026B54",
    },
  },
  {
    id: "TDAT-FM-TSY-002",
    slug: "debt-covenant-model",
    title: "Debt & Covenant Model",
    decision: "Can the business service debt and preserve covenant headroom under downside conditions?",
    description: "Debt roll-forward, cash interest, amortization, leverage, coverage, covenant, and maturity views.",
    domain: "Treasury & Capital",
    roles: ["Treasury", "Corporate Finance", "Credit Analysis", "FP&A"],
    useCases: ["Debt service", "Covenants", "Refinancing"],
    level: "Practitioner",
    status: "Available",
    priority: "P1",
    horizon: "3–10 years",
    setup: "1–2 hours",
    tags: ["Debt", "Interest", "Covenants", "Headroom"],
    compatibility: "Excel 365",
    version: "1.0.0",
    lastTested: "2026-07-13",
    qa: "11 / 11 published checks PASS; 9 / 9 sheets rendered",
    file: {
      path: "debt-covenant-model/model/tdat-debt-covenant-model.xlsx",
      size: "30.7 KB",
      format: ".xlsx",
      macros: false,
      externalLinks: false,
      circularReferences: false,
      sha256: "9E56FC1C142FECE6B65A556B4F728A590C180FB1646571DAF038667A01D05DBB",
    },
  },
  {
    id: "TDAT-FM-RSK-001",
    slug: "credit-underwriting-dscr",
    title: "Credit Underwriting / DSCR",
    decision: "Can the borrower afford the facility across base and stressed cash flows?",
    description: "Borrower cash flow, leverage, DSCR, debt capacity, downside, collateral, and exception tracking.",
    domain: "Credit & Risk",
    roles: ["Credit Analysis", "Enterprise Risk", "Commercial Banking", "Lending"],
    useCases: ["Underwriting", "DSCR", "Debt capacity"],
    level: "Practitioner",
    status: "Available",
    priority: "P1",
    horizon: "1–5 years",
    setup: "1–2 hours",
    tags: ["Credit", "DSCR", "Leverage", "Stress"],
    compatibility: "Excel 365",
    version: "1.0.0",
    lastTested: "2026-07-13",
    qa: "11 / 11 published checks PASS; 9 / 9 sheets rendered",
    file: {
      path: "credit-underwriting-dscr/model/tdat-credit-underwriting-dscr.xlsx",
      size: "30.5 KB",
      format: ".xlsx",
      macros: false,
      externalLinks: false,
      circularReferences: false,
      sha256: "3519B50B751470784A4BF19F3666FAA1FCC9CDB6C75BB7B4D4C5EC0159EB8840",
    },
  },
  {
    id: "TDAT-FM-PF-001",
    slug: "project-finance-lite",
    title: "Project Finance Lite",
    decision: "Is the project bankable, and how do funding, construction, and operating assumptions affect returns?",
    description: "Construction draw, operating cash flow, debt service, DSCR, project IRR, equity IRR, and funding gap.",
    domain: "Project & Real Assets",
    roles: ["Project Finance", "Infrastructure Finance", "Lending", "Investment Analyst"],
    useCases: ["Bankability", "Project returns", "Funding"],
    level: "Advanced",
    status: "Available",
    priority: "P1",
    horizon: "Construction + 10–25 years",
    setup: "3–6 hours",
    tags: ["Project Finance", "DSCR", "IRR", "Construction"],
    compatibility: "Excel 365",
    version: "1.0.0",
    lastTested: "2026-07-13",
    qa: "10 / 10 published checks PASS; 9 / 9 sheets rendered",
    file: {
      path: "project-finance-lite/model/tdat-project-finance-lite.xlsx",
      size: "32.2 KB",
      format: ".xlsx",
      macros: false,
      externalLinks: false,
      circularReferences: false,
      sha256: "E2AA9B330290F4FB15FF177768AEB0387874D08223A7FA0AF398B3CAD50DBF1E",
    },
  },
  {
    id: "TDAT-FM-SME-001",
    slug: "sme-integrated-forecast",
    title: "SME Integrated Forecast",
    decision: "How long can the business operate, when does it break even, and what funding is required?",
    description: "Sales, margin, payroll, working capital, 13-week cash, 24-month forecast, and funding runway.",
    domain: "SME & Startup",
    roles: ["SME Finance", "Founder", "Fractional CFO", "FP&A"],
    useCases: ["Runway", "Break-even", "Funding"],
    level: "Starter",
    status: "Available",
    priority: "P1",
    horizon: "13 weeks + 24 months",
    setup: "1–2 hours",
    tags: ["SME", "Runway", "Break-even", "Cash"],
    compatibility: "Excel 365",
    version: "1.0.0",
    lastTested: "2026-07-13",
    qa: "10 / 10 published checks PASS; 9 / 9 sheets rendered",
    file: {
      path: "sme-integrated-forecast/model/tdat-sme-integrated-forecast.xlsx",
      size: "37.0 KB",
      format: ".xlsx",
      macros: false,
      externalLinks: false,
      circularReferences: false,
      sha256: "4C49001FC7B7210FE48BE7EAD195F8179D5C8C603D8950F2C0AE3DE1B8C92F16",
    },
  },
  {
    id: "TDAT-FM-CORE-002",
    slug: "multi-entity-consolidation-fx",
    title: "Multi-Entity Consolidation & FX",
    decision: "What is the consolidated result after currency translation, eliminations, and entity-level review?",
    description: "Entity inputs, FX translation, eliminations, ownership, consolidated statements, and reconciliation controls.",
    domain: "Core Statements",
    roles: ["Regional Finance", "Controllership", "FP&A", "Accounting"],
    useCases: ["Consolidation", "FX translation", "Eliminations"],
    level: "Advanced",
    status: "Available",
    priority: "P2",
    horizon: "12–60 months",
    setup: "3–6 hours",
    tags: ["Consolidation", "FX", "Eliminations", "Multi-entity"],
    compatibility: "Excel 365",
    version: "1.0.0",
    lastTested: "2026-07-13",
    qa: "11 / 11 published checks PASS; 9 / 9 sheets rendered",
    file: {
      path: "multi-entity-consolidation-fx/model/tdat-multi-entity-consolidation-fx.xlsx",
      size: "29.6 KB",
      format: ".xlsx",
      macros: false,
      externalLinks: false,
      circularReferences: false,
      sha256: "C7370DB52286360CA3E5C845AD987CBB895420AEB687861BBD5AAD02AF83A1F1",
    },
  },
  {
    id: "TDAT-FM-PE-001",
    slug: "lbo-returns-model",
    title: "LBO Returns Model",
    decision: "What leverage, operating improvement, cash sweep, and exit assumptions support sponsor returns?",
    description: "Sources and uses, debt tranches, cash sweep, exit bridge, IRR, MOIC, and downside sensitivities.",
    domain: "Valuation & Transactions",
    roles: ["Private Equity", "Investment Banking", "Leveraged Finance"],
    useCases: ["Sponsor returns", "Leverage", "Exit"],
    level: "Advanced",
    status: "Available",
    priority: "P2",
    horizon: "5–7 years",
    setup: "2–4 hours",
    tags: ["LBO", "IRR", "MOIC", "Cash Sweep"],
    compatibility: "Excel 365",
    version: "1.0.0",
    lastTested: "2026-07-13",
    qa: "12 / 12 published checks PASS; 9 / 9 sheets rendered",
    file: {
      path: "lbo-returns-model/model/tdat-lbo-returns-model.xlsx",
      size: "32.3 KB",
      format: ".xlsx",
      macros: false,
      externalLinks: false,
      circularReferences: false,
      sha256: "497787C7AAF71F3E0B59B2CDE0431D67D1DDB4EF4A56A800910873D86F05FA53",
    },
  },
  {
    id: "TDAT-FM-TSY-003",
    slug: "fx-exposure-hedge",
    title: "FX Exposure & Hedge",
    decision: "Which currency exposures matter, how much is hedged, and what remains under rate shocks?",
    description: "Transaction exposures, hedge coverage, maturity profile, rate sensitivity, and residual P&L/cash risk.",
    domain: "Treasury & Capital",
    roles: ["Treasury", "Enterprise Risk", "Corporate Finance"],
    useCases: ["FX exposure", "Hedge coverage", "Sensitivity"],
    level: "Practitioner",
    status: "Available",
    priority: "P2",
    horizon: "1–24 months",
    setup: "30–90 minutes",
    tags: ["FX", "Hedging", "Treasury", "Sensitivity"],
    compatibility: "Excel 365",
    version: "1.0.0",
    lastTested: "2026-07-13",
    qa: "10 / 10 published checks PASS; 9 / 9 sheets rendered",
    file: {
      path: "fx-exposure-hedge/model/tdat-fx-exposure-hedge.xlsx",
      size: "30.4 KB",
      format: ".xlsx",
      macros: false,
      externalLinks: false,
      circularReferences: false,
      sha256: "25707FC5AB49AF4786DD1013ADE54A5A6109C4E0698AD59D1721FAE083DCCA6A",
    },
  },
  {
    id: "TDAT-FM-RSK-002",
    slug: "ecl-credit-stress-lite",
    title: "ECL / Credit Stress Lite",
    decision: "How do PD, LGD, EAD, staging, and macro scenarios change expected loss?",
    description: "Illustrative expected-credit-loss engine with transparent assumptions, scenario weights, and reconciliation checks.",
    domain: "Credit & Risk",
    roles: ["Credit Risk", "Banking Finance", "Risk Analytics", "Financial Reporting"],
    useCases: ["Expected loss", "Stress", "Provision"],
    level: "Advanced",
    status: "Available",
    priority: "P2",
    horizon: "12-month / lifetime",
    setup: "2–4 hours",
    tags: ["ECL", "PD", "LGD", "EAD"],
    compatibility: "Excel 365",
    version: "1.0.0",
    lastTested: "2026-07-13",
    qa: "11 / 11 published checks PASS; 9 / 9 sheets rendered",
    file: {
      path: "ecl-credit-stress-lite/model/tdat-ecl-credit-stress-lite.xlsx",
      size: "30.5 KB",
      format: ".xlsx",
      macros: false,
      externalLinks: false,
      circularReferences: false,
      sha256: "B0726A7BF75EAC4675B6726CF85766CF92BC96F50FC754C591DE34C057A4B588",
    },
  },
  {
    id: "TDAT-FM-RSK-003",
    slug: "market-portfolio-stress",
    title: "Market Risk / Portfolio Stress",
    decision: "Where do shocks, concentration, and correlations create the largest downside exposure?",
    description: "Scenario shocks, position mapping, concentration, loss attribution, and illustrative risk-limit monitoring.",
    domain: "Credit & Risk",
    roles: ["Market Risk", "Portfolio Risk", "Investment Analyst"],
    useCases: ["Stress testing", "Concentration", "Limits"],
    level: "Advanced",
    status: "Available",
    priority: "P2",
    horizon: "Daily to annual",
    setup: "2–4 hours",
    tags: ["Market Risk", "Stress", "Concentration"],
    compatibility: "Excel 365",
    version: "1.0.0",
    lastTested: "2026-07-13",
    qa: "10 / 10 published checks PASS; 9 / 9 sheets rendered",
    file: {
      path: "market-portfolio-stress/model/tdat-market-portfolio-stress.xlsx",
      size: "30.5 KB",
      format: ".xlsx",
      macros: false,
      externalLinks: false,
      circularReferences: false,
      sha256: "ACBE0933EF9D1FE579ED4DA1FE9DECB1BFEC77C0FC3E0BF0623216B3D554CB3A",
    },
  },
  {
    id: "TDAT-FM-PF-002",
    slug: "debt-sculpting-waterfall",
    title: "Debt Sculpting & Waterfall",
    decision: "What repayment profile and cash waterfall meet coverage constraints while preserving equity value?",
    description: "DSCR-driven sculpting, reserve accounts, waterfall priorities, distributions, and lender/equity returns.",
    domain: "Project & Real Assets",
    roles: ["Project Finance", "Infrastructure Finance", "Structured Finance"],
    useCases: ["Debt sculpting", "Cash waterfall", "Coverage"],
    level: "Advanced",
    status: "Available",
    priority: "P2",
    horizon: "10–30 years",
    setup: "4–8 hours",
    tags: ["Sculpting", "Waterfall", "DSCR", "Reserves"],
    compatibility: "Excel 365",
    version: "1.0.0",
    lastTested: "2026-07-13",
    qa: "12 / 12 published checks PASS; 9 / 9 sheets rendered",
    file: {
      path: "debt-sculpting-waterfall/model/tdat-debt-sculpting-waterfall.xlsx",
      size: "33.1 KB",
      format: ".xlsx",
      macros: false,
      externalLinks: false,
      circularReferences: false,
      sha256: "84AA7FF608A7E4D30566D471CE75E88DBF798C50374952DB8EFFC53CF90BE8DE",
    },
  },
  {
    id: "TDAT-FM-PER-001",
    slug: "personal-budget-net-worth",
    title: "Personal Budget & Net Worth",
    decision: "How should income, spending, debt, savings, and goals be balanced over time?",
    description: "Monthly cash flow, net worth, debt payoff, emergency fund, and goal-tracking template for educational use.",
    domain: "Personal Finance",
    roles: ["Individual / Household", "Financial Education / Learner"],
    useCases: ["Budget", "Net worth", "Debt payoff"],
    level: "Starter",
    status: "Available",
    priority: "P2",
    horizon: "Monthly + 10 years",
    setup: "30–60 minutes",
    tags: ["Personal Finance", "Budget", "Net Worth"],
    compatibility: "Excel 365",
    version: "1.0.0",
    lastTested: "2026-07-13",
    qa: "11 / 11 published checks PASS; 9 / 9 sheets rendered",
    file: {
      path: "personal-budget-net-worth/model/tdat-personal-budget-net-worth.xlsx",
      size: "33.5 KB",
      format: ".xlsx",
      macros: false,
      externalLinks: false,
      circularReferences: false,
      sha256: "6A0AE2844F33794CCF7DDFA2D2BEAFDE8FD79247844D966A4B31731EEFECB62A",
    },
  },
  {
    id: "TDAT-FM-PER-002",
    slug: "retirement-scenario-planner",
    title: "Retirement Scenario Planner",
    decision: "How do contributions, inflation, returns, timing, and drawdown assumptions affect retirement readiness?",
    description: "Educational contribution, accumulation, inflation, withdrawal, and sensitivity model with clear limitations.",
    domain: "Personal Finance",
    roles: ["Individual / Household", "Financial Education / Learner"],
    useCases: ["Retirement", "Contributions", "Drawdown"],
    level: "Practitioner",
    status: "Available",
    priority: "P2",
    horizon: "20–40 years",
    setup: "45–90 minutes",
    tags: ["Retirement", "Inflation", "Scenario"],
    compatibility: "Excel 365",
    version: "1.0.0",
    lastTested: "2026-07-13",
    qa: "11 / 11 published checks PASS; 9 / 9 sheets rendered",
    file: {
      path: "retirement-scenario-planner/model/tdat-retirement-scenario-planner.xlsx",
      size: "43.2 KB",
      format: ".xlsx",
      macros: false,
      externalLinks: false,
      circularReferences: false,
      sha256: "ACD0F500A6BE9EC257AAFB5500D2BC668A3BAAE66AE6279A29A3BA708FDA7483",
    },
  },
  {
    id: "TDAT-FM-COM-001",
    slug: "pricing-margin-waterfall",
    title: "Pricing & Margin Waterfall",
    decision: "Which customer, product, price, discount, mix, and cost actions protect contribution margin?",
    description: "List-to-net pricing, rebates, price-volume-mix, unit economics, customer profitability, and action list.",
    domain: "Planning & Performance",
    roles: ["Commercial Finance", "FP&A", "Pricing Finance", "Sales Finance"],
    useCases: ["Pricing", "Margin", "Customer profitability"],
    level: "Practitioner",
    status: "Available",
    priority: "P2",
    horizon: "Monthly / annual",
    setup: "1–2 hours",
    tags: ["Pricing", "Margin", "Mix", "Profitability"],
    compatibility: "Excel 365",
    version: "1.0.0",
    lastTested: "2026-07-13",
    qa: "9 / 9 published checks PASS; 9 / 9 sheets rendered",
    file: {
      path: "pricing-margin-waterfall/model/tdat-pricing-margin-waterfall.xlsx",
      size: "30.6 KB",
      format: ".xlsx",
      macros: false,
      externalLinks: false,
      circularReferences: false,
      sha256: "1E5070DA84F816EA196910963EA6C5476339153FDFB086E5747EC08E3D04F0F8",
    },
  },
  {
    id: "TDAT-FM-SME-002",
    slug: "saas-unit-economics",
    title: "SaaS Unit Economics",
    decision: "Is growth efficient enough when retention, CAC, LTV, burn, and payback are viewed together?",
    description: "ARR bridge, cohort retention, CAC, LTV, gross margin, burn multiple, runway, and scenario logic.",
    domain: "SME & Startup",
    roles: ["Startup Finance", "FP&A", "Venture Capital", "Founder"],
    useCases: ["Unit economics", "Runway", "Fundraising"],
    level: "Practitioner",
    status: "Available",
    priority: "P2",
    horizon: "24–60 months",
    setup: "1–2 hours",
    tags: ["SaaS", "ARR", "LTV", "CAC"],
    compatibility: "Excel 365",
    version: "1.0.0",
    lastTested: "2026-07-13",
    qa: "10 / 10 published checks PASS; 9 / 9 sheets rendered",
    file: {
      path: "saas-unit-economics/model/tdat-saas-unit-economics.xlsx",
      size: "41.2 KB",
      format: ".xlsx",
      macros: false,
      externalLinks: false,
      circularReferences: false,
      sha256: "C8F0AE910E6F8107CF857F880173659A0244ACA79A39DCFCC2A366EB896AEA19",
    },
  },
];
