window.powerBiProjectDetails = [
  {
    no: "02",
    slug: "driver-based-forecasting",
    folder: "Project 02 - Driver-Based Forecasting",
    title: "Driver-Based Forecasting",
    lens: "Planning model",
    summary: "Scenario model translating volume, cost, headcount, and cash assumptions into a forecast call for FP&A leaders.",
    metrics: [["$273.4M", "base forecast revenue"], ["$21.9M", "ending cash"], ["6.4%", "weighted MAPE"], ["5", "planning pages"]],
    bars: [["Volume", 82], ["Rate", 73], ["Headcount", 61], ["Cash cover", 69]],
    drivers: [["Demand assumption", "+4.8%", false], ["Cost inflation", "-2.2%", true], ["Hiring phasing", "+1.1%", false]],
    actions: [["FP&A", "Compare base, upside, and downside assumptions before forecast signoff."], ["Business owners", "Submit driver changes with quantified EBITDA impact."], ["CFO", "Approve cash guardrail for downside case."]]
  },
  {
    no: "03",
    slug: "ecommerce-executive-performance",
    folder: "Project 03 - Ecommerce Executive Performance",
    title: "Ecommerce Executive Performance",
    lens: "Ecommerce executive KPIs",
    summary: "Executive ecommerce review for revenue, margin, customers, orders, refunds, and operating levers.",
    metrics: [["$48.2M", "GMV"], ["18.6%", "gross margin %"], ["1.24M", "orders"], ["2.1%", "refund rate"]],
    bars: [["GMV", 84], ["Orders", 76], ["AOV", 63], ["Refund control", 71]],
    drivers: [["Category mix", "+$1.8M", false], ["Refund leakage", "-$0.5M", true], ["Repeat buyers", "+7.2%", false]],
    actions: [["Commercial", "Push profitable categories with strong repeat purchase."], ["Ops", "Prioritize refund root-cause by category."], ["Finance", "Refresh margin waterfall for executive review."]]
  },
  {
    no: "04",
    slug: "customer-funnel-conversion",
    folder: "Project 04 - Customer Funnel Conversion",
    title: "Customer Funnel Conversion",
    lens: "Conversion analytics",
    summary: "Acquisition-to-order funnel view tracing leakage by segment, category, and channel.",
    metrics: [["7.8M", "sessions"], ["12.4%", "cart rate"], ["4.9%", "order conversion"], ["-$0.7M", "gross profit leakage"]],
    bars: [["Visit", 92], ["Product view", 73], ["Cart", 54], ["Order", 38]],
    drivers: [["Checkout friction", "-1.3 pts", true], ["Paid search quality", "+0.8 pts", false], ["Mobile speed", "-0.5 pts", true]],
    actions: [["Product", "Fix checkout step with highest leakage."], ["Marketing", "Shift spend to channels with purchase-ready traffic."], ["Finance", "Size conversion upside by segment."]]
  },
  {
    no: "05",
    slug: "retention-cohort-ltv",
    folder: "Project 05 - Retention Cohort LTV",
    title: "Retention Cohort LTV",
    lens: "Customer lifecycle",
    summary: "Cohort and LTV dashboard exposing retention decay, churn signals, customer value, and win-back priorities.",
    metrics: [["68%", "M3 retention"], ["3.4x", "LTV/CAC"], ["11.2%", "churn risk"], ["$8.6M", "retained revenue value"]],
    bars: [["Month 1", 86], ["Month 3", 68], ["Month 6", 55], ["Month 12", 43]],
    drivers: [["First order quality", "+6.1 pts", false], ["Dormant cohort", "-4.4 pts", true], ["Win-back offer", "+$0.9M", false]],
    actions: [["CRM", "Target dormant high-LTV cohorts."], ["Commercial", "Improve first-order experience for new users."], ["Finance", "Track LTV recovery versus incentive cost."]]
  },
  {
    no: "06",
    slug: "marketing-campaign-roi",
    folder: "Project 06 - Marketing Campaign ROI",
    title: "Marketing Campaign ROI",
    lens: "Marketing finance",
    summary: "Campaign ROI review showing which channels to scale, pause, or fix based on spend efficiency.",
    metrics: [["4.8x", "ROAS"], ["$18.40", "CAC"], ["31%", "spend below hurdle"], ["$1.2M", "redeployable spend"]],
    bars: [["Search", 82], ["Affiliate", 74], ["Social", 45], ["Display", 32]],
    drivers: [["Search intent", "+$0.8M", false], ["Display waste", "-$0.4M", true], ["Creative fatigue", "-12%", true]],
    actions: [["Marketing", "Scale high-intent campaigns."], ["Finance", "Reallocate spend from low-ROAS channels."], ["Growth", "Refresh creative for fatigued segments."]]
  },
  {
    no: "07",
    slug: "marketplace-seller-performance",
    folder: "Project 07 - Marketplace Seller Performance",
    title: "Marketplace Seller Performance",
    lens: "Marketplace operations",
    summary: "Seller performance dashboard connecting GMV movement, fulfillment, cancellation, stock availability, and account-manager actions.",
    metrics: [["119", "active sellers"], ["97.7%", "fulfillment SLA"], ["8.3%", "cancel rate"], ["$211.3K", "seller GMV"]],
    bars: [["Fulfillment", 98], ["Stock availability", 91], ["Watch sellers", 36], ["Rating", 83]],
    drivers: [["GMV momentum", "+2.8%", false], ["Cancellation pressure", "+0.3 pts", true], ["Watch sellers", "43", true]],
    actions: [["Marketplace", "Protect GMV momentum in top seller accounts."], ["Operations", "Reduce cancellation pressure above the 8.0% guardrail."], ["Account managers", "Work the 43-seller watchlist across 5 owner queues."]]
  },
  {
    no: "08",
    slug: "digital-payments-profitability",
    folder: "Project 08 - Digital Payments Profitability",
    title: "Digital Payments Profitability",
    lens: "Payments profitability",
    summary: "Digital payments FP&A dashboard rebuilt as a management pack: GMV, revenue, contribution margin, take rate, risk leakage, and scenario CM uplift.",
    metrics: [["$41.4M", "GMV"], ["$540.3K", "revenue"], ["$201.9K", "contribution margin"], ["1.31%", "take rate"]],
    bars: [["GMV", 82], ["Revenue", 72], ["CM", 67], ["Take rate", 65]],
    drivers: [["GMV MoM", "+1.0%", false], ["Refund rate", "2.19%", true], ["Scenario CM uplift", "+$40.4K", false]],
    actions: [["Commercial", "Review low-fee, high-volume merchant contracts."], ["Finance", "Use bridge and scenario CM to set pricing guardrails."], ["Risk / Ops", "Work refund and chargeback leakage watchlist."]]
  },
  {
    no: "09",
    slug: "bnpl-credit-risk-provision",
    folder: "Project 09 - BNPL Credit Risk Provision",
    title: "BNPL Credit Risk Provision",
    lens: "Credit risk command center",
    summary: "BNPL credit-risk command center upgraded with Current Lens, native KPI cards with sparklines, delinquency/vintage diagnostics, collections owner queues, and provision governance.",
    metrics: [["$1.6M", "current loan book"], ["25.0%", "30+ DPD"], ["65.9%", "approval rate"], ["$20.2K", "provision held"]],
    bars: [["Current", 9], ["1-29 DPD", 65], ["30-59 DPD", 14], ["60+ DPD", 11]],
    drivers: [["Vintage pressure", "-$18.4K ECL", true], ["Approval discipline", "65.9%", false], ["Provision cover", "+$1.8K buffer", false]],
    actions: [["Risk", "Tighten weak merchant cohorts and monitor the Current Lens risk signal."], ["Collections", "Prioritize accounts before 60+ DPD migration by queue owner."], ["Finance", "Refresh provision sensitivity and coverage before CFO review."]]
  },
  {
    no: "10",
    slug: "aml-fraud-monitoring",
    folder: "Project 10 - AML Fraud Monitoring",
    title: "AML Fraud Monitoring",
    lens: "Risk operations",
    summary: "AML command center connecting alert exposure, suspicious-case conversion, case SLA, rule precision, false positives, and accountable governance actions.",
    metrics: [["6,611", "alerts"], ["66.1%", "SLA compliance"], ["35.4%", "false positives"], ["$420.1M", "alert exposure"]],
    bars: [["Alert rate", 18.4], ["SLA compliance", 66.1], ["Rule precision", 64.6], ["False positives", 35.4]],
    drivers: [["Alert-to-case conversion", "53.8%", false], ["Overdue backlog", "1,207 cases", true], ["Average case age", "2.4 days", false]],
    actions: [["Risk Ops", "Prioritize high-exposure alert clusters and overdue investigations."], ["Rule Governance", "Tune high-volume rules where false positives dilute precision."], ["Compliance", "Track queue ownership, SLA recovery, and approved rule changes."]]
  },
  {
    no: "11",
    slug: "neobank-growth-retention-ltv",
    folder: "Project 11 - Neobank Growth Retention LTV",
    title: "Neobank Growth Retention LTV",
    lens: "Neobank growth",
    summary: "Three-page growth economics pack connecting acquisition scale, onboarding conversion, mature-cohort retention, churn, payback, and LTV to accountable actions.",
    metrics: [["9.5K", "new users"], ["19.3K", "active users"], ["1.9K", "funded accounts"], ["2.1x", "LTV/CAC"]],
    bars: [["KYC completion", 63], ["Activation", 38], ["Funded", 20], ["M3 retained", 89]],
    drivers: [["M3 cohort retention", "88.7%", false], ["Paid type economics", "1.0x LTV/CAC", true], ["Lifecycle email economics", "6.2x LTV/CAC", false]],
    actions: [["Growth", "Scale partner and referral lanes inside conversion guardrails."], ["Retention", "Work the 1,235-user risk queue by expected retained value."], ["Finance", "Hold paid budget until CAC, payback, and ROI gates recover."]]
  },
  {
    no: "12",
    slug: "wealthtech-aum-client-retention",
    folder: "Project 12 - WealthTech AUM Client Retention",
    title: "WealthTech AUM Client Retention",
    lens: "Wealth analytics",
    summary: "AUM retention dashboard combining portfolio mix, client risk, suitability, and retention actions.",
    metrics: [["$811.1M", "AUM"], ["$2.9M", "net new money"], ["181", "rebalance-needed clients"], ["$4.9M", "churn-risk AUM"]],
    bars: [["AUM", 89], ["Net flow", 42], ["Suitability", 59], ["Churn risk", 18]],
    drivers: [["Market effect", "+$17.0M", false], ["Outflows", "-$25.3M", true], ["Rebalance queue", "181 clients", true]],
    actions: [["Advisory", "Prioritize retained-AUM action queue for HNW/UHNW clients."], ["Risk", "Resolve suitability and rebalance exceptions before outflows accelerate."], ["Finance", "Track latest-month AUM roll-forward, NNM, and churn-risk exposure."]]
  },
  {
    no: "13",
    slug: "regional-fpa-consolidation",
    folder: "Project 13 - Regional FP&A Consolidation",
    title: "Regional FP&A Consolidation",
    lens: "Regional MNC finance",
    summary: "Regional consolidation view for country/entity variance, FX translation, eliminations, and close exceptions.",
    metrics: [["7", "entities"], ["3", "currencies"], ["100%", "P&L tie-out"], ["$2.6M", "FX translation variance"]],
    bars: [["Country A", 78], ["Country B", 63], ["Country C", 70], ["Elims", 57]],
    drivers: [["FX translation", "-$0.8M", true], ["Entity margin", "+$1.1M", false], ["Elimination timing", "-$0.3M", true]],
    actions: [["Regional FP&A", "Lock country variance owner comments."], ["Accounting", "Clear elimination timing breaks."], ["CFO", "Review FX bridge before board pack."]]
  },
  {
    no: "14",
    slug: "treasury-working-capital",
    folder: "Project 14 - Treasury Working Capital",
    title: "Treasury Working Capital",
    lens: "Treasury command center",
    summary: "Treasury working-capital cockpit linking liquidity, runway, AR/AP execution, FX exposure, forecast accuracy, risk ownership, and action queues.",
    metrics: [["$92.5M", "available liquidity"], ["$82.3M", "liquidity headroom"], ["263.9 wks", "cash runway"], ["66.0%", "overdue AR"]],
    bars: [["Liquidity", 92], ["Headroom", 82], ["AR pressure", 66], ["FX hedge gap", 55]],
    drivers: [["13W net flow", "-$3.8M", true], ["AP due 14d", "$4.6M", true], ["Open risks", "61", true]],
    actions: [["Treasury", "Protect headroom and sequence payments against the 13-week cash view."], ["Collections", "Work overdue AR by customer risk and owner queue."], ["Finance", "Refresh FX, forecast error, and runway calls before CFO review."]]
  },
  {
    no: "15",
    slug: "saas-cfo-metrics",
    folder: "Project 15 - SaaS CFO Metrics",
    title: "SaaS CFO Metrics",
    lens: "CFO metrics",
    summary: "CFO metrics pack upgraded with native composite KPI cards, integrated sparklines, dynamic Current Lens, and board-ready ARR/retention/efficiency views.",
    metrics: [["$25.3M", "ARR"], ["99.5%", "NRR"], ["1.2", "CAC payback months"], ["2.9%", "logo churn"]],
    bars: [["ARR", 86], ["NRR", 70], ["CAC payback", 92], ["Churn", 29]],
    drivers: [["Expansion ARR", "+$673.7K", false], ["Net New ARR", "-$24.8K", true], ["Forecast accuracy", "99.9%", false]],
    actions: [["Sales", "Protect expansion in healthy cohorts."], ["CS", "Work the renewal-risk account queue."], ["Finance", "Use the Current Lens, KPI sparklines, and forecast/cash signals for board review."]]
  },
  {
    no: "16",
    slug: "manufacturing-cost-fpa",
    folder: "Project 16 - Manufacturing Cost FP&A",
    title: "Manufacturing Cost FP&A",
    lens: "Cost FP&A",
    summary: "Cost FP&A pack decomposing standard cost variance, yield, capacity, inventory days, and margin recovery actions.",
    metrics: [["$7.3M", "cost variance"], ["86%", "capacity use"], ["94.1%", "yield"], ["48", "inventory days"]],
    bars: [["Material", 66], ["Labor", 58], ["Overhead", 61], ["Yield", 76]],
    drivers: [["Material price", "-$1.2M", true], ["Yield recovery", "+$0.5M", false], ["Idle capacity", "-$0.7M", true]],
    actions: [["Operations", "Recover yield on underperforming lines."], ["Procurement", "Negotiate material price variance."], ["Finance", "Track margin recovery by plant."]]
  },
  {
    no: "17",
    slug: "logistics-trade-lane-profitability",
    folder: "Project 17 - Logistics Trade Lane Profitability",
    title: "Logistics Trade Lane Profitability",
    lens: "Commercial finance",
    summary: "Lane-level profitability view showing customers, services, and lanes needing repricing or renegotiation.",
    metrics: [["$11.1M", "net revenue"], ["$614K", "gross profit"], ["5.6%", "GP margin"], ["$255K", "reprice exposure"]],
    bars: [["FCL", 78], ["Air", 22], ["LCL", 18], ["Road", 8]],
    drivers: [["Loss lanes", "-$143K", true], ["Reprice exposure", "-$255K", true], ["Top FCL lanes", "+$452K", false]],
    actions: [["Commercial", "Reprice negative-margin lanes and low-yield accounts."], ["Ops", "Reduce claims, demurrage, and exception cost."], ["Finance", "Track lane margin and owner action queue."]]
  },
  {
    no: "18",
    slug: "esg-carbon-finance",
    folder: "Project 18 - ESG Carbon Finance",
    title: "ESG Carbon Finance",
    lens: "ESG finance",
    summary: "CFO-style ESG finance dashboard linking emissions, supplier intensity, carbon cost exposure, abatement ROI, and risk governance.",
    metrics: [["719.5K", "total tCO2e"], ["$64.8M", "carbon cost at $90/t"], ["123.1", "tCO2e per $M"], ["29.1K", "target gap"]],
    bars: [["Scope 1", 62], ["Scope 2", 21], ["Scope 3", 88], ["Abatement", 74]],
    drivers: [["Carbon price", "-$64.8M", true], ["Scope 3 exposure", "-371.6K tCO2e", true], ["Abatement ROI", "+44.9%", false]],
    actions: [["Procurement", "Prioritize high-intensity supplier follow-up."], ["Finance", "Refresh carbon price exposure and scenario cost sensitivity."], ["ESG", "Sequence abatement initiatives by ROI and implementation status."]]
  },
  {
    no: "19",
    slug: "finance-data-quality-bi-governance",
    folder: "Project 19 - Finance Data Quality BI Governance",
    title: "Finance Data Quality BI Governance",
    lens: "Finance governance",
    summary: "Governance BI monitoring reconciliation breaks, data quality risk, refresh reliability, and owner action queues.",
    metrics: [["99.6%", "refresh SLA"], ["42", "data checks"], ["8", "recon breaks"], ["3", "owner escalations"]],
    bars: [["Refresh", 91], ["Completeness", 84], ["Reconciliation", 67], ["Ownership", 74]],
    drivers: [["Refresh reliability", "+6 pts", false], ["Mapping gaps", "-4 pts", true], ["Owner SLA", "+3 pts", false]],
    actions: [["Data owner", "Resolve high-risk mapping gaps."], ["Finance", "Review recon breaks before close."], ["BI", "Monitor refresh exceptions and alerts."]]
  }
];
