window.powerBiProjectDetails = [
  {
    no: "02",
    slug: "driver-based-forecasting",
    folder: "Project 02 - Driver-Based Forecasting",
    title: "Driver-Based Forecasting",
    lens: "Planning model",
    summary: "Scenario model translating volume, cost, headcount, and cash assumptions into a forecast call for FP&A leaders.",
    metrics: [["$273.4M", "base forecast revenue"], ["$21.9M", "ending cash"], ["6.4%", "weighted MAPE"], ["5", "planning pages"]],
    bars: [["Volume", 82], ["Rate", 73], ["Headcount", 61], ["Cash cover", 69]],
    drivers: [["Demand assumption", "+4.8%", false], ["Cost inflation", "-2.2%", true], ["Hiring phasing", "+1.1%", false]],
    actions: [["FP&A", "Compare base, upside, and downside assumptions before forecast signoff."], ["Business owners", "Submit driver changes with quantified EBITDA impact."], ["CFO", "Approve cash guardrail for downside case."]]
  },
  {
    no: "03",
    slug: "ecommerce-executive-performance",
    folder: "Project 03 - Ecommerce Executive Performance",
    title: "Ecommerce Executive Performance",
    lens: "Ecommerce executive KPIs",
    summary: "Executive ecommerce review for revenue, margin, customers, orders, refunds, and operating levers.",
    metrics: [["$48.2M", "GMV"], ["18.6%", "gross margin %"], ["1.24M", "orders"], ["2.1%", "refund rate"]],
    bars: [["GMV", 84], ["Orders", 76], ["AOV", 63], ["Refund control", 71]],
    drivers: [["Category mix", "+$1.8M", false], ["Refund leakage", "-$0.5M", true], ["Repeat buyers", "+7.2%", false]],
    actions: [["Commercial", "Push profitable categories with strong repeat purchase."], ["Ops", "Prioritize refund root-cause by category."], ["Finance", "Refresh margin waterfall for executive review."]]
  },
  {
    no: "04",
    slug: "customer-funnel-conversion",
    folder: "Project 04 - Customer Funnel Conversion",
    title: "Customer Funnel Conversion",
    lens: "Conversion analytics",
    summary: "Acquisition-to-order funnel view tracing leakage by segment, category, and channel.",
    metrics: [["7.8M", "sessions"], ["12.4%", "cart rate"], ["4.9%", "order conversion"], ["-$0.7M", "gross profit leakage"]],
    bars: [["Visit", 92], ["Product view", 73], ["Cart", 54], ["Order", 38]],
    drivers: [["Checkout friction", "-1.3 pts", true], ["Paid search quality", "+0.8 pts", false], ["Mobile speed", "-0.5 pts", true]],
    actions: [["Product", "Fix checkout step with highest leakage."], ["Marketing", "Shift spend to channels with purchase-ready traffic."], ["Finance", "Size conversion upside by segment."]]
  },
  {
    no: "05",
    slug: "retention-cohort-ltv",
    folder: "Project 05 - Retention Cohort LTV",
    title: "Retention Cohort LTV",
    lens: "Customer lifecycle",
    summary: "Cohort and LTV dashboard exposing retention decay, churn signals, customer value, and win-back priorities.",
    metrics: [["68%", "M3 retention"], ["3.4x", "LTV/CAC"], ["11.2%", "churn risk"], ["$8.6M", "retained revenue value"]],
    bars: [["Month 1", 86], ["Month 3", 68], ["Month 6", 55], ["Month 12", 43]],
    drivers: [["First order quality", "+6.1 pts", false], ["Dormant cohort", "-4.4 pts", true], ["Win-back offer", "+$0.9M", false]],
    actions: [["CRM", "Target dormant high-LTV cohorts."], ["Commercial", "Improve first-order experience for new users."], ["Finance", "Track LTV recovery versus incentive cost."]]
  },
  {
    no: "06",
    slug: "marketing-campaign-roi",
    folder: "Project 06 - Marketing Campaign ROI",
    title: "Marketing Campaign ROI",
    lens: "Marketing finance",
    summary: "Campaign ROI review showing which channels to scale, pause, or fix based on spend efficiency.",
    metrics: [["4.8x", "ROAS"], ["$18.40", "CAC"], ["31%", "spend below hurdle"], ["$1.2M", "redeployable spend"]],
    bars: [["Search", 82], ["Affiliate", 74], ["Social", 45], ["Display", 32]],
    drivers: [["Search intent", "+$0.8M", false], ["Display waste", "-$0.4M", true], ["Creative fatigue", "-12%", true]],
    actions: [["Marketing", "Scale high-intent campaigns."], ["Finance", "Reallocate spend from low-ROAS channels."], ["Growth", "Refresh creative for fatigued segments."]]
  },
  {
    no: "07",
    slug: "marketplace-seller-performance",
    folder: "Project 07 - Marketplace Seller Performance",
    title: "Marketplace Seller Performance",
    lens: "Marketplace operations",
    summary: "Seller performance dashboard ranking GMV, fulfillment, cancellation, rating, stock risk, and growth actions.",
    metrics: [["2,840", "active sellers"], ["96.1%", "fulfillment SLA"], ["3.8%", "cancel rate"], ["$3.1M", "GMV growth pool"]],
    bars: [["Top sellers", 86], ["Fulfillment", 80], ["Stock health", 64], ["Rating", 72]],
    drivers: [["Top seller expansion", "+$1.4M", false], ["Cancellation risk", "-$0.3M", true], ["Stockout pressure", "-$0.6M", true]],
    actions: [["Marketplace", "Prioritize seller enablement for high-GMV accounts."], ["Operations", "Resolve stockout and cancellation root causes."], ["Finance", "Quantify margin from seller quality actions."]]
  },
  {
    no: "08",
    slug: "digital-payments-profitability",
    folder: "Project 08 - Digital Payments Profitability",
    title: "Digital Payments Profitability",
    lens: "Payments profitability",
    summary: "Payments profitability dashboard linking merchant mix, transaction drivers, margin scenarios, and fee economics.",
    metrics: [["$92.5M", "TPV"], ["1.28%", "take rate"], ["38%", "gross margin %"], ["$0.09", "unit profit"]],
    bars: [["TPV", 90], ["Take rate", 63], ["Cost to serve", 58], ["Merchant mix", 70]],
    drivers: [["Enterprise TPV", "+$2.2M", false], ["Processing cost", "-$0.7M", true], ["Fee optimization", "+$0.4M", false]],
    actions: [["Commercial", "Review low-fee enterprise contracts."], ["Finance", "Model fee tiers by merchant segment."], ["Ops", "Track processing cost exceptions."]]
  },
  {
    no: "09",
    slug: "bnpl-credit-risk-provision",
    folder: "Project 09 - BNPL Credit Risk Provision",
    title: "BNPL Credit Risk Provision",
    lens: "Credit risk",
    summary: "Credit-risk provision dashboard for loan book trend, delinquency, collections SLA, and provision pressure.",
    metrics: [["$41.6M", "loan book"], ["6.7%", "30+ DPD"], ["2.9%", "loss rate"], ["$1.1M", "ECL provision gap"]],
    bars: [["Current", 82], ["1-30 DPD", 54], ["31-60 DPD", 31], ["60+ DPD", 18]],
    drivers: [["Vintage mix", "-$0.5M", true], ["Collections lift", "+$0.3M", false], ["Merchant cohort", "-$0.2M", true]],
    actions: [["Risk", "Tighten exposure for weak merchant cohorts."], ["Collections", "Focus accounts before 60+ DPD migration."], ["Finance", "Update provision sensitivity for CFO review."]]
  },
  {
    no: "10",
    slug: "aml-fraud-monitoring",
    folder: "Project 10 - AML Fraud Monitoring",
    title: "AML Fraud Monitoring",
    lens: "Risk operations",
    summary: "Fraud monitoring view surfacing suspicious patterns, case backlog, rule performance, and AML actions.",
    metrics: [["12,480", "alerts"], ["91%", "SLA cleared"], ["3.2%", "false positives"], ["$0.8M", "exposure flagged"]],
    bars: [["Rule hits", 74], ["Case SLA", 83], ["False positives", 58], ["Exposure", 66]],
    drivers: [["New pattern cluster", "-$0.4M", true], ["Rule tuning", "+9 pts", false], ["Backlog aging", "-6 pts", true]],
    actions: [["Risk Ops", "Escalate high-exposure clusters."], ["Analytics", "Tune rules with high false-positive rate."], ["Compliance", "Track SLA aging by owner."]]
  },
  {
    no: "11",
    slug: "neobank-growth-retention-ltv",
    folder: "Project 11 - Neobank Growth Retention LTV",
    title: "Neobank Growth Retention LTV",
    lens: "Neobank growth",
    summary: "Growth and retention pack tying onboarding funnel, cohorts, churn, marketing ROI, and LTV to profitable growth.",
    metrics: [["520K", "funded accounts"], ["72%", "M2 active"], ["2.7x", "LTV/CAC"], ["8.8%", "monthly churn"]],
    bars: [["Onboarded", 88], ["Funded", 69], ["Active", 60], ["Retained", 52]],
    drivers: [["Funding activation", "+5.4 pts", false], ["Dormant churn", "-3.1 pts", true], ["Channel quality", "+0.6x", false]],
    actions: [["Growth", "Fund users earlier in onboarding."], ["CRM", "Reduce churn in first 60 days."], ["Finance", "Tie channel budget to LTV/CAC."]]
  },
  {
    no: "12",
    slug: "wealthtech-aum-client-retention",
    folder: "Project 12 - WealthTech AUM Client Retention",
    title: "WealthTech AUM Client Retention",
    lens: "Wealth analytics",
    summary: "AUM retention dashboard combining portfolio mix, client risk, suitability, and retention actions.",
    metrics: [["$1.8B", "AUM"], ["94.2%", "client retention"], ["7.6%", "outflow risk"], ["$46M", "at-risk AUM"]],
    bars: [["AUM", 89], ["Retention", 84], ["Suitability", 72], ["Outflow risk", 39]],
    drivers: [["Advisor coverage", "+$18M", false], ["Market drawdown", "-$11M", true], ["Suitability gap", "-$7M", true]],
    actions: [["Advisory", "Contact high-AUM at-risk clients."], ["Risk", "Resolve suitability exceptions."], ["Finance", "Track fee revenue exposure."]]
  },
  {
    no: "13",
    slug: "regional-fpa-consolidation",
    folder: "Project 13 - Regional FP&A Consolidation",
    title: "Regional FP&A Consolidation",
    lens: "Regional MNC finance",
    summary: "Regional consolidation view for country/entity variance, FX translation, eliminations, and close exceptions.",
    metrics: [["7", "entities"], ["3", "currencies"], ["100%", "P&L tie-out"], ["$2.6M", "FX translation variance"]],
    bars: [["Country A", 78], ["Country B", 63], ["Country C", 70], ["Elims", 57]],
    drivers: [["FX translation", "-$0.8M", true], ["Entity margin", "+$1.1M", false], ["Elimination timing", "-$0.3M", true]],
    actions: [["Regional FP&A", "Lock country variance owner comments."], ["Accounting", "Clear elimination timing breaks."], ["CFO", "Review FX bridge before board pack."]]
  },
  {
    no: "14",
    slug: "treasury-working-capital",
    folder: "Project 14 - Treasury Working Capital",
    title: "Treasury Working Capital",
    lens: "Treasury and cash",
    summary: "Treasury view prioritizing AR, DSO, cash runway, FX exposure, liquidity, and collection actions.",
    metrics: [["$24.7M", "cash balance"], ["51", "DSO days"], ["$6.2M", "overdue AR"], ["14.8", "cash runway months"]],
    bars: [["Cash", 77], ["AR quality", 58], ["DSO", 48], ["Collections", 68]],
    drivers: [["Overdue AR", "-$1.6M", true], ["Supplier terms", "+$0.7M", false], ["FX exposure", "-$0.4M", true]],
    actions: [["Treasury", "Prioritize top overdue customers."], ["Commercial", "Escalate collection promises by owner."], ["Finance", "Refresh cash runway under downside case."]]
  },
  {
    no: "15",
    slug: "saas-cfo-metrics",
    folder: "Project 15 - SaaS CFO Metrics",
    title: "SaaS CFO Metrics",
    lens: "CFO metrics",
    summary: "CFO metrics pack for ARR, NRR/GRR, churn, CAC payback, cohort economics, and forecast health.",
    metrics: [["$18.4M", "ARR"], ["112%", "NRR"], ["14", "CAC payback months"], ["7.1%", "logo churn"]],
    bars: [["ARR", 80], ["NRR", 75], ["CAC payback", 56], ["Churn", 42]],
    drivers: [["Expansion ARR", "+$1.1M", false], ["SMB churn", "-$0.4M", true], ["Sales efficiency", "+0.2x", false]],
    actions: [["Sales", "Prioritize expansion in healthy cohorts."], ["CS", "Target SMB churn accounts."], ["Finance", "Connect ARR bridge to board forecast."]]
  },
  {
    no: "16",
    slug: "manufacturing-cost-fpa",
    folder: "Project 16 - Manufacturing Cost FP&A",
    title: "Manufacturing Cost FP&A",
    lens: "Cost FP&A",
    summary: "Cost FP&A pack decomposing standard cost variance, yield, capacity, inventory days, and margin recovery actions.",
    metrics: [["$7.3M", "cost variance"], ["86%", "capacity use"], ["94.1%", "yield"], ["48", "inventory days"]],
    bars: [["Material", 66], ["Labor", 58], ["Overhead", 61], ["Yield", 76]],
    drivers: [["Material price", "-$1.2M", true], ["Yield recovery", "+$0.5M", false], ["Idle capacity", "-$0.7M", true]],
    actions: [["Operations", "Recover yield on underperforming lines."], ["Procurement", "Negotiate material price variance."], ["Finance", "Track margin recovery by plant."]]
  },
  {
    no: "17",
    slug: "logistics-trade-lane-profitability",
    folder: "Project 17 - Logistics Trade Lane Profitability",
    title: "Logistics Trade Lane Profitability",
    lens: "Commercial finance",
    summary: "Lane-level profitability view showing customers, services, and lanes needing repricing or renegotiation.",
    metrics: [["$11.1M", "net revenue"], ["$614K", "gross profit"], ["5.6%", "GP margin"], ["$255K", "reprice exposure"]],
    bars: [["FCL", 78], ["Air", 22], ["LCL", 18], ["Road", 8]],
    drivers: [["Loss lanes", "-$143K", true], ["Reprice exposure", "-$255K", true], ["Top FCL lanes", "+$452K", false]],
    actions: [["Commercial", "Reprice negative-margin lanes and low-yield accounts."], ["Ops", "Reduce claims, demurrage, and exception cost."], ["Finance", "Track lane margin and owner action queue."]]
  },
  {
    no: "18",
    slug: "esg-carbon-finance",
    folder: "Project 18 - ESG Carbon Finance",
    title: "ESG Carbon Finance",
    lens: "ESG finance",
    summary: "CFO-style ESG finance dashboard linking emissions, supplier intensity, carbon cost exposure, abatement ROI, and risk governance.",
    metrics: [["719.5K", "total tCO2e"], ["$64.8M", "carbon cost at $90/t"], ["123.1", "tCO2e per $M"], ["29.1K", "target gap"]],
    bars: [["Scope 1", 62], ["Scope 2", 21], ["Scope 3", 88], ["Abatement", 74]],
    drivers: [["Carbon price", "-$64.8M", true], ["Scope 3 exposure", "-371.6K tCO2e", true], ["Abatement ROI", "+44.9%", false]],
    actions: [["Procurement", "Prioritize high-intensity supplier follow-up."], ["Finance", "Refresh carbon price exposure and scenario cost sensitivity."], ["ESG", "Sequence abatement initiatives by ROI and implementation status."]]
  },
  {
    no: "19",
    slug: "finance-data-quality-bi-governance",
    folder: "Project 19 - Finance Data Quality BI Governance",
    title: "Finance Data Quality BI Governance",
    lens: "Finance governance",
    summary: "Governance BI monitoring reconciliation breaks, data quality risk, refresh reliability, and owner action queues.",
    metrics: [["99.6%", "refresh SLA"], ["42", "data checks"], ["8", "recon breaks"], ["3", "owner escalations"]],
    bars: [["Refresh", 91], ["Completeness", 84], ["Reconciliation", 67], ["Ownership", 74]],
    drivers: [["Refresh reliability", "+6 pts", false], ["Mapping gaps", "-4 pts", true], ["Owner SLA", "+3 pts", false]],
    actions: [["Data owner", "Resolve high-risk mapping gaps."], ["Finance", "Review recon breaks before close."], ["BI", "Monitor refresh exceptions and alerts."]]
  }
];
